// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChildProfile = `-- name: CreateChildProfile :one
INSERT INTO kids.child_profiles (parent_user_id, display_name, birth_year, age_years, avatar_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, parent_user_id, display_name, birth_year, age_years, avatar_key, is_active, created_at, updated_at
`

type CreateChildProfileParams struct {
	ParentUserID uuid.UUID `json:"parent_user_id"`
	DisplayName  string    `json:"display_name"`
	BirthYear    *int32    `json:"birth_year"`
	AgeYears     int32     `json:"age_years"`
	AvatarKey    *string   `json:"avatar_key"`
}

func (q *Queries) CreateChildProfile(ctx context.Context, arg CreateChildProfileParams) (KidsChildProfile, error) {
	row := q.db.QueryRow(ctx, createChildProfile,
		arg.ParentUserID,
		arg.DisplayName,
		arg.BirthYear,
		arg.AgeYears,
		arg.AvatarKey,
	)
	var i KidsChildProfile
	err := row.Scan(
		&i.ID,
		&i.ParentUserID,
		&i.DisplayName,
		&i.BirthYear,
		&i.AgeYears,
		&i.AvatarKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateChildProfile = `-- name: DeactivateChildProfile :exec
UPDATE kids.child_profiles SET is_active = false, updated_at = now()
WHERE id = $1 AND parent_user_id = $2
`

type DeactivateChildProfileParams struct {
	ID           uuid.UUID `json:"id"`
	ParentUserID uuid.UUID `json:"parent_user_id"`
}

func (q *Queries) DeactivateChildProfile(ctx context.Context, arg DeactivateChildProfileParams) error {
	_, err := q.db.Exec(ctx, deactivateChildProfile, arg.ID, arg.ParentUserID)
	return err
}

const deleteContentApproval = `-- name: DeleteContentApproval :exec
DELETE FROM kids.content_approvals WHERE child_profile_id = $1 AND book_id = $2
`

type DeleteContentApprovalParams struct {
	ChildProfileID uuid.UUID `json:"child_profile_id"`
	BookID         uuid.UUID `json:"book_id"`
}

func (q *Queries) DeleteContentApproval(ctx context.Context, arg DeleteContentApprovalParams) error {
	_, err := q.db.Exec(ctx, deleteContentApproval, arg.ChildProfileID, arg.BookID)
	return err
}

const getAllowedPromptByID = `-- name: GetAllowedPromptByID :one
SELECT id, label, prompt_text, min_age, max_age, sort_order, is_active FROM kids.allowed_prompts WHERE id = $1 AND is_active
`

func (q *Queries) GetAllowedPromptByID(ctx context.Context, id uuid.UUID) (KidsAllowedPrompt, error) {
	row := q.db.QueryRow(ctx, getAllowedPromptByID, id)
	var i KidsAllowedPrompt
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.PromptText,
		&i.MinAge,
		&i.MaxAge,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const getChildProfileByID = `-- name: GetChildProfileByID :one
SELECT id, parent_user_id, display_name, birth_year, age_years, avatar_key, is_active, created_at, updated_at FROM kids.child_profiles WHERE id = $1
`

func (q *Queries) GetChildProfileByID(ctx context.Context, id uuid.UUID) (KidsChildProfile, error) {
	row := q.db.QueryRow(ctx, getChildProfileByID, id)
	var i KidsChildProfile
	err := row.Scan(
		&i.ID,
		&i.ParentUserID,
		&i.DisplayName,
		&i.BirthYear,
		&i.AgeYears,
		&i.AvatarKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChildProfileForParent = `-- name: GetChildProfileForParent :one
SELECT id, parent_user_id, display_name, birth_year, age_years, avatar_key, is_active, created_at, updated_at FROM kids.child_profiles WHERE id = $1 AND parent_user_id = $2
`

type GetChildProfileForParentParams struct {
	ID           uuid.UUID `json:"id"`
	ParentUserID uuid.UUID `json:"parent_user_id"`
}

// مالکیت همیشه با parent_user_id چک می‌شود، نه فقط با id. اگر یک بار
// فقط id چک شود، هر والدی می‌تواند پروفایل کودک والد دیگر را بخواند —
// و این بدترین نوع نشتی داده در این محصول است.
func (q *Queries) GetChildProfileForParent(ctx context.Context, arg GetChildProfileForParentParams) (KidsChildProfile, error) {
	row := q.db.QueryRow(ctx, getChildProfileForParent, arg.ID, arg.ParentUserID)
	var i KidsChildProfile
	err := row.Scan(
		&i.ID,
		&i.ParentUserID,
		&i.DisplayName,
		&i.BirthYear,
		&i.AgeYears,
		&i.AvatarKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContentApproval = `-- name: GetContentApproval :one
SELECT id, child_profile_id, book_id, decision, decided_by, decided_at FROM kids.content_approvals WHERE child_profile_id = $1 AND book_id = $2
`

type GetContentApprovalParams struct {
	ChildProfileID uuid.UUID `json:"child_profile_id"`
	BookID         uuid.UUID `json:"book_id"`
}

func (q *Queries) GetContentApproval(ctx context.Context, arg GetContentApprovalParams) (KidsContentApproval, error) {
	row := q.db.QueryRow(ctx, getContentApproval, arg.ChildProfileID, arg.BookID)
	var i KidsContentApproval
	err := row.Scan(
		&i.ID,
		&i.ChildProfileID,
		&i.BookID,
		&i.Decision,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const getParentalControls = `-- name: GetParentalControls :one
SELECT child_profile_id, daily_limit_minutes, allowed_from_minute, allowed_to_minute, max_content_age, approval_mode, exit_pin_hash, autodownload_wifi_only, updated_at FROM kids.parental_controls WHERE child_profile_id = $1
`

func (q *Queries) GetParentalControls(ctx context.Context, childProfileID uuid.UUID) (KidsParentalControl, error) {
	row := q.db.QueryRow(ctx, getParentalControls, childProfileID)
	var i KidsParentalControl
	err := row.Scan(
		&i.ChildProfileID,
		&i.DailyLimitMinutes,
		&i.AllowedFromMinute,
		&i.AllowedToMinute,
		&i.MaxContentAge,
		&i.ApprovalMode,
		&i.ExitPinHash,
		&i.AutodownloadWifiOnly,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllowedPromptsForAge = `-- name: ListAllowedPromptsForAge :many
SELECT id, label, prompt_text, min_age, max_age, sort_order, is_active FROM kids.allowed_prompts
WHERE is_active AND $1::int BETWEEN min_age AND max_age
ORDER BY sort_order
`

func (q *Queries) ListAllowedPromptsForAge(ctx context.Context, dollar_1 int32) ([]KidsAllowedPrompt, error) {
	rows, err := q.db.Query(ctx, listAllowedPromptsForAge, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KidsAllowedPrompt
	for rows.Next() {
		var i KidsAllowedPrompt
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.PromptText,
			&i.MinAge,
			&i.MaxAge,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChildProfilesForParent = `-- name: ListChildProfilesForParent :many
SELECT id, parent_user_id, display_name, birth_year, age_years, avatar_key, is_active, created_at, updated_at FROM kids.child_profiles
WHERE parent_user_id = $1 AND is_active
ORDER BY created_at
`

func (q *Queries) ListChildProfilesForParent(ctx context.Context, parentUserID uuid.UUID) ([]KidsChildProfile, error) {
	rows, err := q.db.Query(ctx, listChildProfilesForParent, parentUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KidsChildProfile
	for rows.Next() {
		var i KidsChildProfile
		if err := rows.Scan(
			&i.ID,
			&i.ParentUserID,
			&i.DisplayName,
			&i.BirthYear,
			&i.AgeYears,
			&i.AvatarKey,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentApprovals = `-- name: ListContentApprovals :many
SELECT ca.id, ca.child_profile_id, ca.book_id, ca.decision, ca.decided_by, ca.decided_at, b.title, b.cover_url
FROM kids.content_approvals ca
JOIN catalog.books b ON b.id = ca.book_id
WHERE ca.child_profile_id = $1
ORDER BY ca.decided_at DESC
`

type ListContentApprovalsRow struct {
	ID             uuid.UUID `json:"id"`
	ChildProfileID uuid.UUID `json:"child_profile_id"`
	BookID         uuid.UUID `json:"book_id"`
	Decision       string    `json:"decision"`
	DecidedBy      uuid.UUID `json:"decided_by"`
	DecidedAt      time.Time `json:"decided_at"`
	Title          string    `json:"title"`
	CoverUrl       *string   `json:"cover_url"`
}

func (q *Queries) ListContentApprovals(ctx context.Context, childProfileID uuid.UUID) ([]ListContentApprovalsRow, error) {
	rows, err := q.db.Query(ctx, listContentApprovals, childProfileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContentApprovalsRow
	for rows.Next() {
		var i ListContentApprovalsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChildProfileID,
			&i.BookID,
			&i.Decision,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Title,
			&i.CoverUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setExitPin = `-- name: SetExitPin :exec
UPDATE kids.parental_controls SET exit_pin_hash = $2, updated_at = now()
WHERE child_profile_id = $1
`

type SetExitPinParams struct {
	ChildProfileID uuid.UUID `json:"child_profile_id"`
	ExitPinHash    *string   `json:"exit_pin_hash"`
}

func (q *Queries) SetExitPin(ctx context.Context, arg SetExitPinParams) error {
	_, err := q.db.Exec(ctx, setExitPin, arg.ChildProfileID, arg.ExitPinHash)
	return err
}

const updateChildProfile = `-- name: UpdateChildProfile :one
UPDATE kids.child_profiles
SET display_name = coalesce($1::text, display_name),
    age_years    = coalesce($2::int, age_years),
    birth_year   = coalesce($3::int, birth_year),
    avatar_key   = coalesce($4::text, avatar_key),
    updated_at   = now()
WHERE id = $5 AND parent_user_id = $6
RETURNING id, parent_user_id, display_name, birth_year, age_years, avatar_key, is_active, created_at, updated_at
`

type UpdateChildProfileParams struct {
	DisplayName  *string   `json:"display_name"`
	AgeYears     *int32    `json:"age_years"`
	BirthYear    *int32    `json:"birth_year"`
	AvatarKey    *string   `json:"avatar_key"`
	ID           uuid.UUID `json:"id"`
	ParentUserID uuid.UUID `json:"parent_user_id"`
}

func (q *Queries) UpdateChildProfile(ctx context.Context, arg UpdateChildProfileParams) (KidsChildProfile, error) {
	row := q.db.QueryRow(ctx, updateChildProfile,
		arg.DisplayName,
		arg.AgeYears,
		arg.BirthYear,
		arg.AvatarKey,
		arg.ID,
		arg.ParentUserID,
	)
	var i KidsChildProfile
	err := row.Scan(
		&i.ID,
		&i.ParentUserID,
		&i.DisplayName,
		&i.BirthYear,
		&i.AgeYears,
		&i.AvatarKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertContentApproval = `-- name: UpsertContentApproval :one
INSERT INTO kids.content_approvals (child_profile_id, book_id, decision, decided_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (child_profile_id, book_id) DO UPDATE SET
    decision = EXCLUDED.decision, decided_by = EXCLUDED.decided_by, decided_at = now()
RETURNING id, child_profile_id, book_id, decision, decided_by, decided_at
`

type UpsertContentApprovalParams struct {
	ChildProfileID uuid.UUID `json:"child_profile_id"`
	BookID         uuid.UUID `json:"book_id"`
	Decision       string    `json:"decision"`
	DecidedBy      uuid.UUID `json:"decided_by"`
}

func (q *Queries) UpsertContentApproval(ctx context.Context, arg UpsertContentApprovalParams) (KidsContentApproval, error) {
	row := q.db.QueryRow(ctx, upsertContentApproval,
		arg.ChildProfileID,
		arg.BookID,
		arg.Decision,
		arg.DecidedBy,
	)
	var i KidsContentApproval
	err := row.Scan(
		&i.ID,
		&i.ChildProfileID,
		&i.BookID,
		&i.Decision,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const upsertParentalControls = `-- name: UpsertParentalControls :one
INSERT INTO kids.parental_controls (
    child_profile_id, daily_limit_minutes, allowed_from_minute, allowed_to_minute,
    max_content_age, approval_mode, autodownload_wifi_only, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (child_profile_id) DO UPDATE SET
    daily_limit_minutes    = EXCLUDED.daily_limit_minutes,
    allowed_from_minute    = EXCLUDED.allowed_from_minute,
    allowed_to_minute      = EXCLUDED.allowed_to_minute,
    max_content_age        = EXCLUDED.max_content_age,
    approval_mode          = EXCLUDED.approval_mode,
    autodownload_wifi_only = EXCLUDED.autodownload_wifi_only,
    updated_at             = now()
RETURNING child_profile_id, daily_limit_minutes, allowed_from_minute, allowed_to_minute, max_content_age, approval_mode, exit_pin_hash, autodownload_wifi_only, updated_at
`

type UpsertParentalControlsParams struct {
	ChildProfileID       uuid.UUID `json:"child_profile_id"`
	DailyLimitMinutes    int32     `json:"daily_limit_minutes"`
	AllowedFromMinute    int32     `json:"allowed_from_minute"`
	AllowedToMinute      int32     `json:"allowed_to_minute"`
	MaxContentAge        int32     `json:"max_content_age"`
	ApprovalMode         string    `json:"approval_mode"`
	AutodownloadWifiOnly bool      `json:"autodownload_wifi_only"`
}

func (q *Queries) UpsertParentalControls(ctx context.Context, arg UpsertParentalControlsParams) (KidsParentalControl, error) {
	row := q.db.QueryRow(ctx, upsertParentalControls,
		arg.ChildProfileID,
		arg.DailyLimitMinutes,
		arg.AllowedFromMinute,
		arg.AllowedToMinute,
		arg.MaxContentAge,
		arg.ApprovalMode,
		arg.AutodownloadWifiOnly,
	)
	var i KidsParentalControl
	err := row.Scan(
		&i.ChildProfileID,
		&i.DailyLimitMinutes,
		&i.AllowedFromMinute,
		&i.AllowedToMinute,
		&i.MaxContentAge,
		&i.ApprovalMode,
		&i.ExitPinHash,
		&i.AutodownloadWifiOnly,
		&i.UpdatedAt,
	)
	return i, err
}
