// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChildProfile(ctx context.Context, arg CreateChildProfileParams) (KidsChildProfile, error)
	DeactivateChildProfile(ctx context.Context, arg DeactivateChildProfileParams) error
	DeleteContentApproval(ctx context.Context, arg DeleteContentApprovalParams) error
	GetAllowedPromptByID(ctx context.Context, id uuid.UUID) (KidsAllowedPrompt, error)
	GetChildProfileByID(ctx context.Context, id uuid.UUID) (KidsChildProfile, error)
	// مالکیت همیشه با parent_user_id چک می‌شود، نه فقط با id. اگر یک بار
	// فقط id چک شود، هر والدی می‌تواند پروفایل کودک والد دیگر را بخواند —
	// و این بدترین نوع نشتی داده در این محصول است.
	GetChildProfileForParent(ctx context.Context, arg GetChildProfileForParentParams) (KidsChildProfile, error)
	GetContentApproval(ctx context.Context, arg GetContentApprovalParams) (KidsContentApproval, error)
	GetParentalControls(ctx context.Context, childProfileID uuid.UUID) (KidsParentalControl, error)
	ListAllowedPromptsForAge(ctx context.Context, dollar_1 int32) ([]KidsAllowedPrompt, error)
	ListChildProfilesForParent(ctx context.Context, parentUserID uuid.UUID) ([]KidsChildProfile, error)
	ListContentApprovals(ctx context.Context, childProfileID uuid.UUID) ([]ListContentApprovalsRow, error)
	SetExitPin(ctx context.Context, arg SetExitPinParams) error
	UpdateChildProfile(ctx context.Context, arg UpdateChildProfileParams) (KidsChildProfile, error)
	UpsertContentApproval(ctx context.Context, arg UpsertContentApprovalParams) (KidsContentApproval, error)
	UpsertParentalControls(ctx context.Context, arg UpsertParentalControlsParams) (KidsParentalControl, error)
}

var _ Querier = (*Queries)(nil)
