// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveDevicesForUser = `-- name: CountActiveDevicesForUser :one
SELECT count(*) FROM identity.devices
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) CountActiveDevicesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveDevicesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO identity.devices (user_id, platform, push_token, app_version, last_active_at)
VALUES ($1, $2, $3, $4, now())
RETURNING id, user_id, platform, push_token, app_version, last_active_at, created_at, device_fingerprint, revoked_at, name
`

type CreateDeviceParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Platform   string    `json:"platform"`
	PushToken  *string   `json:"push_token"`
	AppVersion *string   `json:"app_version"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (IdentityDevice, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.UserID,
		arg.Platform,
		arg.PushToken,
		arg.AppVersion,
	)
	var i IdentityDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PushToken,
		&i.AppVersion,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.DeviceFingerprint,
		&i.RevokedAt,
		&i.Name,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, user_id, platform, push_token, app_version, last_active_at, created_at, device_fingerprint, revoked_at, name FROM identity.devices WHERE id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (IdentityDevice, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i IdentityDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PushToken,
		&i.AppVersion,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.DeviceFingerprint,
		&i.RevokedAt,
		&i.Name,
	)
	return i, err
}

const listActiveDevicesForUser = `-- name: ListActiveDevicesForUser :many
SELECT id, user_id, platform, push_token, app_version, last_active_at, created_at, device_fingerprint, revoked_at, name FROM identity.devices
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY last_active_at DESC
`

func (q *Queries) ListActiveDevicesForUser(ctx context.Context, userID uuid.UUID) ([]IdentityDevice, error) {
	rows, err := q.db.Query(ctx, listActiveDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityDevice
	for rows.Next() {
		var i IdentityDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.PushToken,
			&i.AppVersion,
			&i.LastActiveAt,
			&i.CreatedAt,
			&i.DeviceFingerprint,
			&i.RevokedAt,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeDevice = `-- name: RevokeDevice :exec
UPDATE identity.devices SET revoked_at = now() WHERE id = $1 AND user_id = $2
`

type RevokeDeviceParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeDevice, arg.ID, arg.UserID)
	return err
}

const revokeOldestActiveDevice = `-- name: RevokeOldestActiveDevice :one
UPDATE identity.devices d SET revoked_at = now()
WHERE d.id = (
    SELECT inner_d.id FROM identity.devices inner_d
    WHERE inner_d.user_id = $1 AND inner_d.revoked_at IS NULL
    ORDER BY inner_d.last_active_at ASC
    LIMIT 1
)
RETURNING id, user_id, platform, push_token, app_version, last_active_at, created_at, device_fingerprint, revoked_at, name
`

func (q *Queries) RevokeOldestActiveDevice(ctx context.Context, userID uuid.UUID) (IdentityDevice, error) {
	row := q.db.QueryRow(ctx, revokeOldestActiveDevice, userID)
	var i IdentityDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PushToken,
		&i.AppVersion,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.DeviceFingerprint,
		&i.RevokedAt,
		&i.Name,
	)
	return i, err
}

const revokeRefreshTokensForDevice = `-- name: RevokeRefreshTokensForDevice :exec
UPDATE identity.refresh_tokens SET revoked_at = now()
WHERE device_id = $1 AND revoked_at IS NULL
`

// وقتی دستگاه باطل می‌شود، refresh token همان دستگاه هم باید بمیرد،
// وگرنه «خروج از این دستگاه» فقط ظاهری است.
func (q *Queries) RevokeRefreshTokensForDevice(ctx context.Context, deviceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensForDevice, deviceID)
	return err
}

const touchDevice = `-- name: TouchDevice :exec
UPDATE identity.devices
SET last_active_at = now()
WHERE id = $1
`

func (q *Queries) TouchDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDevice, id)
	return err
}

const upsertDevice = `-- name: UpsertDevice :one
INSERT INTO identity.devices (user_id, platform, push_token, app_version, device_fingerprint, name, last_active_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (user_id, device_fingerprint) WHERE device_fingerprint IS NOT NULL
DO UPDATE SET
    platform       = EXCLUDED.platform,
    push_token     = coalesce(EXCLUDED.push_token, identity.devices.push_token),
    app_version    = EXCLUDED.app_version,
    name           = coalesce(EXCLUDED.name, identity.devices.name),
    revoked_at     = NULL,
    last_active_at = now()
RETURNING id, user_id, platform, push_token, app_version, last_active_at, created_at, device_fingerprint, revoked_at, name
`

type UpsertDeviceParams struct {
	UserID            uuid.UUID `json:"user_id"`
	Platform          string    `json:"platform"`
	PushToken         *string   `json:"push_token"`
	AppVersion        *string   `json:"app_version"`
	DeviceFingerprint *string   `json:"device_fingerprint"`
	Name              *string   `json:"name"`
}

// ثبت دستگاه با fingerprint: بدون ON CONFLICT، هر بار ورود روی همان
// گوشی یک ردیف تازه می‌سازد و سقف پخش هم‌زمان بی‌معنی می‌شود.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (IdentityDevice, error) {
	row := q.db.QueryRow(ctx, upsertDevice,
		arg.UserID,
		arg.Platform,
		arg.PushToken,
		arg.AppVersion,
		arg.DeviceFingerprint,
		arg.Name,
	)
	var i IdentityDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.PushToken,
		&i.AppVersion,
		&i.LastActiveAt,
		&i.CreatedAt,
		&i.DeviceFingerprint,
		&i.RevokedAt,
		&i.Name,
	)
	return i, err
}
