// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeOTPCode = `-- name: ConsumeOTPCode :exec
UPDATE identity.otp_codes
SET consumed_at = now()
WHERE id = $1
`

func (q *Queries) ConsumeOTPCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTPCode, id)
	return err
}

const countOTPRequestsSince = `-- name: CountOTPRequestsSince :one
SELECT count(*) FROM identity.otp_codes
WHERE phone_number = $1 AND created_at > $2
`

type CountOTPRequestsSinceParams struct {
	PhoneNumber string    `json:"phone_number"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CountOTPRequestsSince(ctx context.Context, arg CountOTPRequestsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOTPRequestsSince, arg.PhoneNumber, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOTPCode = `-- name: CreateOTPCode :one
INSERT INTO identity.otp_codes (phone_number, code_hash, purpose, expires_at, max_attempts)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, phone_number, code_hash, purpose, attempt_count, max_attempts, expires_at, consumed_at, created_at
`

type CreateOTPCodeParams struct {
	PhoneNumber string    `json:"phone_number"`
	CodeHash    string    `json:"code_hash"`
	Purpose     string    `json:"purpose"`
	ExpiresAt   time.Time `json:"expires_at"`
	MaxAttempts int32     `json:"max_attempts"`
}

func (q *Queries) CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (IdentityOtpCode, error) {
	row := q.db.QueryRow(ctx, createOTPCode,
		arg.PhoneNumber,
		arg.CodeHash,
		arg.Purpose,
		arg.ExpiresAt,
		arg.MaxAttempts,
	)
	var i IdentityOtpCode
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.CodeHash,
		&i.Purpose,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestActiveOTP = `-- name: GetLatestActiveOTP :one
SELECT id, phone_number, code_hash, purpose, attempt_count, max_attempts, expires_at, consumed_at, created_at FROM identity.otp_codes
WHERE phone_number = $1
  AND purpose = $2
  AND consumed_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestActiveOTPParams struct {
	PhoneNumber string `json:"phone_number"`
	Purpose     string `json:"purpose"`
}

func (q *Queries) GetLatestActiveOTP(ctx context.Context, arg GetLatestActiveOTPParams) (IdentityOtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestActiveOTP, arg.PhoneNumber, arg.Purpose)
	var i IdentityOtpCode
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.CodeHash,
		&i.Purpose,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempt = `-- name: IncrementOTPAttempt :one
UPDATE identity.otp_codes
SET attempt_count = attempt_count + 1
WHERE id = $1
RETURNING id, phone_number, code_hash, purpose, attempt_count, max_attempts, expires_at, consumed_at, created_at
`

func (q *Queries) IncrementOTPAttempt(ctx context.Context, id uuid.UUID) (IdentityOtpCode, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempt, id)
	var i IdentityOtpCode
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.CodeHash,
		&i.Purpose,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}
