// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConsumeOTPCode(ctx context.Context, id uuid.UUID) error
	CountActiveDevicesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountOTPRequestsSince(ctx context.Context, arg CountOTPRequestsSinceParams) (int64, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (IdentityDevice, error)
	CreateOTPCode(ctx context.Context, arg CreateOTPCodeParams) (IdentityOtpCode, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (IdentityRefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error)
	GetActiveRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error)
	GetDeviceByID(ctx context.Context, id uuid.UUID) (IdentityDevice, error)
	GetLatestActiveOTP(ctx context.Context, arg GetLatestActiveOTPParams) (IdentityOtpCode, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error)
	GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (IdentityUser, error)
	GrantUserRole(ctx context.Context, arg GrantUserRoleParams) error
	IncrementOTPAttempt(ctx context.Context, id uuid.UUID) (IdentityOtpCode, error)
	ListActiveDevicesForUser(ctx context.Context, userID uuid.UUID) ([]IdentityDevice, error)
	ListUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error)
	MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error
	RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
	RevokeDevice(ctx context.Context, arg RevokeDeviceParams) error
	RevokeOldestActiveDevice(ctx context.Context, userID uuid.UUID) (IdentityDevice, error)
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error
	// کشتن کل خانواده توکن. وقتی یک توکن باطل‌شده دوباره استفاده می‌شود یعنی
	// یا کاربر یا مهاجم نسخه‌ای دارد که نباید داشته باشد؛ در آن حالت هیچ‌کدام
	// نباید ادامه دهند.
	RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error
	// وقتی دستگاه باطل می‌شود، refresh token همان دستگاه هم باید بمیرد،
	// وگرنه «خروج از این دستگاه» فقط ظاهری است.
	RevokeRefreshTokensForDevice(ctx context.Context, deviceID pgtype.UUID) error
	RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error
	SetKidsModePreference(ctx context.Context, arg SetKidsModePreferenceParams) (IdentityUser, error)
	SetUserStatus(ctx context.Context, arg SetUserStatusParams) (IdentityUser, error)
	TouchDevice(ctx context.Context, id uuid.UUID) error
	TouchUserLastSeen(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (IdentityUser, error)
	// ثبت دستگاه با fingerprint: بدون ON CONFLICT، هر بار ورود روی همان
	// گوشی یک ردیف تازه می‌سازد و سقف پخش هم‌زمان بی‌معنی می‌شود.
	UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (IdentityDevice, error)
}

var _ Querier = (*Queries)(nil)
