// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO identity.refresh_tokens (user_id, device_id, token_hash, expires_at, family_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, device_id, token_hash, expires_at, revoked_at, created_at, family_id, replaced_by_id, used_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	DeviceID  pgtype.UUID `json:"device_id"`
	TokenHash string      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	FamilyID  uuid.UUID   `json:"family_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.DeviceID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.FamilyID,
	)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedByID,
		&i.UsedAt,
	)
	return i, err
}

const getActiveRefreshTokenByHash = `-- name: GetActiveRefreshTokenByHash :one
SELECT id, user_id, device_id, token_hash, expires_at, revoked_at, created_at, family_id, replaced_by_id, used_at FROM identity.refresh_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActiveRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, getActiveRefreshTokenByHash, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedByID,
		&i.UsedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, device_id, token_hash, expires_at, revoked_at, created_at, family_id, replaced_by_id, used_at FROM identity.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeviceID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedByID,
		&i.UsedAt,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE identity.refresh_tokens
SET used_at = now(), revoked_at = now(), replaced_by_id = $1::uuid
WHERE id = $2
`

type MarkRefreshTokenUsedParams struct {
	ReplacedByID pgtype.UUID `json:"replaced_by_id"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.ReplacedByID, arg.ID)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE identity.refresh_tokens
SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE identity.refresh_tokens
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE identity.refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE identity.refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

// کشتن کل خانواده توکن. وقتی یک توکن باطل‌شده دوباره استفاده می‌شود یعنی
// یا کاربر یا مهاجم نسخه‌ای دارد که نباید داشته باشد؛ در آن حالت هیچ‌کدام
// نباید ادامه دهند.
func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	return err
}
