// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO identity.users (phone_number, full_name)
VALUES ($1, $2)
RETURNING id, phone_number, full_name, email, role, status, kids_mode_enabled, created_at, updated_at, suspended_reason, deleted_at, last_seen_at
`

type CreateUserParams struct {
	PhoneNumber string  `json:"phone_number"`
	FullName    *string `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.PhoneNumber, arg.FullName)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KidsModeEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone_number, full_name, email, role, status, kids_mode_enabled, created_at, updated_at, suspended_reason, deleted_at, last_seen_at FROM identity.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KidsModeEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, phone_number, full_name, email, role, status, kids_mode_enabled, created_at, updated_at, suspended_reason, deleted_at, last_seen_at FROM identity.users WHERE phone_number = $1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KidsModeEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const grantUserRole = `-- name: GrantUserRole :exec
INSERT INTO identity.user_roles (user_id, role)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GrantUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) GrantUserRole(ctx context.Context, arg GrantUserRoleParams) error {
	_, err := q.db.Exec(ctx, grantUserRole, arg.UserID, arg.Role)
	return err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role FROM identity.user_roles WHERE user_id = $1 ORDER BY role
`

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserRole = `-- name: RevokeUserRole :exec
DELETE FROM identity.user_roles WHERE user_id = $1 AND role = $2
`

type RevokeUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) RevokeUserRole(ctx context.Context, arg RevokeUserRoleParams) error {
	_, err := q.db.Exec(ctx, revokeUserRole, arg.UserID, arg.Role)
	return err
}

const setKidsModePreference = `-- name: SetKidsModePreference :one
UPDATE identity.users
SET kids_mode_enabled = $2, updated_at = now()
WHERE id = $1
RETURNING id, phone_number, full_name, email, role, status, kids_mode_enabled, created_at, updated_at, suspended_reason, deleted_at, last_seen_at
`

type SetKidsModePreferenceParams struct {
	ID              uuid.UUID `json:"id"`
	KidsModeEnabled bool      `json:"kids_mode_enabled"`
}

func (q *Queries) SetKidsModePreference(ctx context.Context, arg SetKidsModePreferenceParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, setKidsModePreference, arg.ID, arg.KidsModeEnabled)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KidsModeEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const setUserStatus = `-- name: SetUserStatus :one
UPDATE identity.users
SET status = $2, suspended_reason = $3, updated_at = now()
WHERE id = $1
RETURNING id, phone_number, full_name, email, role, status, kids_mode_enabled, created_at, updated_at, suspended_reason, deleted_at, last_seen_at
`

type SetUserStatusParams struct {
	ID              uuid.UUID `json:"id"`
	Status          string    `json:"status"`
	SuspendedReason *string   `json:"suspended_reason"`
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, setUserStatus, arg.ID, arg.Status, arg.SuspendedReason)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KidsModeEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchUserLastSeen = `-- name: TouchUserLastSeen :exec
UPDATE identity.users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchUserLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchUserLastSeen, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE identity.users
SET full_name  = coalesce($1::text, full_name),
    email      = coalesce($2::text, email),
    updated_at = now()
WHERE id = $3
RETURNING id, phone_number, full_name, email, role, status, kids_mode_enabled, created_at, updated_at, suspended_reason, deleted_at, last_seen_at
`

type UpdateUserProfileParams struct {
	FullName *string   `json:"full_name"`
	Email    *string   `json:"email"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.FullName, arg.Email, arg.ID)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.FullName,
		&i.Email,
		&i.Role,
		&i.Status,
		&i.KidsModeEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedReason,
		&i.DeletedAt,
		&i.LastSeenAt,
	)
	return i, err
}
