// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audio_assets.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const createAudioAsset = `-- name: CreateAudioAsset :one
INSERT INTO media.audio_assets (audio_edition_id, storage_key, format, bitrate_kbps, duration_seconds, checksum)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, audio_edition_id, storage_key, format, bitrate_kbps, duration_seconds, checksum, created_at
`

type CreateAudioAssetParams struct {
	AudioEditionID  uuid.UUID `json:"audio_edition_id"`
	StorageKey      string    `json:"storage_key"`
	Format          string    `json:"format"`
	BitrateKbps     int32     `json:"bitrate_kbps"`
	DurationSeconds int32     `json:"duration_seconds"`
	Checksum        *string   `json:"checksum"`
}

func (q *Queries) CreateAudioAsset(ctx context.Context, arg CreateAudioAssetParams) (MediaAudioAsset, error) {
	row := q.db.QueryRow(ctx, createAudioAsset,
		arg.AudioEditionID,
		arg.StorageKey,
		arg.Format,
		arg.BitrateKbps,
		arg.DurationSeconds,
		arg.Checksum,
	)
	var i MediaAudioAsset
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.StorageKey,
		&i.Format,
		&i.BitrateKbps,
		&i.DurationSeconds,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const createTranscodeJob = `-- name: CreateTranscodeJob :one
INSERT INTO media.transcode_jobs (audio_edition_id, status, input_key, output_format)
VALUES ($1, 'pending', $2, $3)
RETURNING id, audio_edition_id, status, input_key, output_format, error, created_at, updated_at
`

type CreateTranscodeJobParams struct {
	AudioEditionID uuid.UUID `json:"audio_edition_id"`
	InputKey       *string   `json:"input_key"`
	OutputFormat   *string   `json:"output_format"`
}

func (q *Queries) CreateTranscodeJob(ctx context.Context, arg CreateTranscodeJobParams) (MediaTranscodeJob, error) {
	row := q.db.QueryRow(ctx, createTranscodeJob, arg.AudioEditionID, arg.InputKey, arg.OutputFormat)
	var i MediaTranscodeJob
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.Status,
		&i.InputKey,
		&i.OutputFormat,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAudioAssetByID = `-- name: GetAudioAssetByID :one
SELECT id, audio_edition_id, storage_key, format, bitrate_kbps, duration_seconds, checksum, created_at FROM media.audio_assets WHERE id = $1
`

func (q *Queries) GetAudioAssetByID(ctx context.Context, id uuid.UUID) (MediaAudioAsset, error) {
	row := q.db.QueryRow(ctx, getAudioAssetByID, id)
	var i MediaAudioAsset
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.StorageKey,
		&i.Format,
		&i.BitrateKbps,
		&i.DurationSeconds,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const getAudioAssetForEditionFormat = `-- name: GetAudioAssetForEditionFormat :one
SELECT id, audio_edition_id, storage_key, format, bitrate_kbps, duration_seconds, checksum, created_at FROM media.audio_assets WHERE audio_edition_id = $1 AND format = $2
`

type GetAudioAssetForEditionFormatParams struct {
	AudioEditionID uuid.UUID `json:"audio_edition_id"`
	Format         string    `json:"format"`
}

func (q *Queries) GetAudioAssetForEditionFormat(ctx context.Context, arg GetAudioAssetForEditionFormatParams) (MediaAudioAsset, error) {
	row := q.db.QueryRow(ctx, getAudioAssetForEditionFormat, arg.AudioEditionID, arg.Format)
	var i MediaAudioAsset
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.StorageKey,
		&i.Format,
		&i.BitrateKbps,
		&i.DurationSeconds,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const getPrimaryAudioAssetForEdition = `-- name: GetPrimaryAudioAssetForEdition :one
SELECT id, audio_edition_id, storage_key, format, bitrate_kbps, duration_seconds, checksum, created_at FROM media.audio_assets
WHERE audio_edition_id = $1
ORDER BY (format = 'm4a') DESC
LIMIT 1
`

func (q *Queries) GetPrimaryAudioAssetForEdition(ctx context.Context, audioEditionID uuid.UUID) (MediaAudioAsset, error) {
	row := q.db.QueryRow(ctx, getPrimaryAudioAssetForEdition, audioEditionID)
	var i MediaAudioAsset
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.StorageKey,
		&i.Format,
		&i.BitrateKbps,
		&i.DurationSeconds,
		&i.Checksum,
		&i.CreatedAt,
	)
	return i, err
}

const getTranscodeJobByID = `-- name: GetTranscodeJobByID :one
SELECT id, audio_edition_id, status, input_key, output_format, error, created_at, updated_at FROM media.transcode_jobs WHERE id = $1
`

func (q *Queries) GetTranscodeJobByID(ctx context.Context, id uuid.UUID) (MediaTranscodeJob, error) {
	row := q.db.QueryRow(ctx, getTranscodeJobByID, id)
	var i MediaTranscodeJob
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.Status,
		&i.InputKey,
		&i.OutputFormat,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAudioAssetsForEdition = `-- name: ListAudioAssetsForEdition :many
SELECT id, audio_edition_id, storage_key, format, bitrate_kbps, duration_seconds, checksum, created_at FROM media.audio_assets WHERE audio_edition_id = $1 ORDER BY format
`

func (q *Queries) ListAudioAssetsForEdition(ctx context.Context, audioEditionID uuid.UUID) ([]MediaAudioAsset, error) {
	rows, err := q.db.Query(ctx, listAudioAssetsForEdition, audioEditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAudioAsset
	for rows.Next() {
		var i MediaAudioAsset
		if err := rows.Scan(
			&i.ID,
			&i.AudioEditionID,
			&i.StorageKey,
			&i.Format,
			&i.BitrateKbps,
			&i.DurationSeconds,
			&i.Checksum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudioAssetsForEditions = `-- name: ListAudioAssetsForEditions :many
SELECT id, audio_edition_id, storage_key, format, bitrate_kbps, duration_seconds, checksum, created_at FROM media.audio_assets
WHERE audio_edition_id = ANY($1::uuid[])
`

func (q *Queries) ListAudioAssetsForEditions(ctx context.Context, audioEditionIds []uuid.UUID) ([]MediaAudioAsset, error) {
	rows, err := q.db.Query(ctx, listAudioAssetsForEditions, audioEditionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAudioAsset
	for rows.Next() {
		var i MediaAudioAsset
		if err := rows.Scan(
			&i.ID,
			&i.AudioEditionID,
			&i.StorageKey,
			&i.Format,
			&i.BitrateKbps,
			&i.DurationSeconds,
			&i.Checksum,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTranscodeJobs = `-- name: ListPendingTranscodeJobs :many
SELECT id, audio_edition_id, status, input_key, output_format, error, created_at, updated_at FROM media.transcode_jobs
WHERE status = 'pending'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListPendingTranscodeJobs(ctx context.Context, limit int32) ([]MediaTranscodeJob, error) {
	rows, err := q.db.Query(ctx, listPendingTranscodeJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaTranscodeJob
	for rows.Next() {
		var i MediaTranscodeJob
		if err := rows.Scan(
			&i.ID,
			&i.AudioEditionID,
			&i.Status,
			&i.InputKey,
			&i.OutputFormat,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTranscodeJobStatus = `-- name: SetTranscodeJobStatus :one
UPDATE media.transcode_jobs
SET status = $2, error = $3, updated_at = now()
WHERE id = $1
RETURNING id, audio_edition_id, status, input_key, output_format, error, created_at, updated_at
`

type SetTranscodeJobStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
	Error  *string   `json:"error"`
}

func (q *Queries) SetTranscodeJobStatus(ctx context.Context, arg SetTranscodeJobStatusParams) (MediaTranscodeJob, error) {
	row := q.db.QueryRow(ctx, setTranscodeJobStatus, arg.ID, arg.Status, arg.Error)
	var i MediaTranscodeJob
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.Status,
		&i.InputKey,
		&i.OutputFormat,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAudioAsset = `-- name: UpsertAudioAsset :one
INSERT INTO media.audio_assets (audio_edition_id, storage_key, format, duration_seconds)
VALUES ($1, $2, $3, $4)
ON CONFLICT (audio_edition_id, format) DO UPDATE
SET storage_key      = EXCLUDED.storage_key,
    duration_seconds = EXCLUDED.duration_seconds
RETURNING id
`

type UpsertAudioAssetParams struct {
	AudioEditionID  uuid.UUID `json:"audio_edition_id"`
	StorageKey      string    `json:"storage_key"`
	Format          string    `json:"format"`
	DurationSeconds int32     `json:"duration_seconds"`
}

func (q *Queries) UpsertAudioAsset(ctx context.Context, arg UpsertAudioAssetParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAudioAsset,
		arg.AudioEditionID,
		arg.StorageKey,
		arg.Format,
		arg.DurationSeconds,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
