// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAudioAsset(ctx context.Context, arg CreateAudioAssetParams) (MediaAudioAsset, error)
	CreateTranscodeJob(ctx context.Context, arg CreateTranscodeJobParams) (MediaTranscodeJob, error)
	GetAudioAssetByID(ctx context.Context, id uuid.UUID) (MediaAudioAsset, error)
	GetAudioAssetForEditionFormat(ctx context.Context, arg GetAudioAssetForEditionFormatParams) (MediaAudioAsset, error)
	GetPrimaryAudioAssetForEdition(ctx context.Context, audioEditionID uuid.UUID) (MediaAudioAsset, error)
	GetTranscodeJobByID(ctx context.Context, id uuid.UUID) (MediaTranscodeJob, error)
	ListAudioAssetsForEdition(ctx context.Context, audioEditionID uuid.UUID) ([]MediaAudioAsset, error)
	ListAudioAssetsForEditions(ctx context.Context, audioEditionIds []uuid.UUID) ([]MediaAudioAsset, error)
	ListPendingTranscodeJobs(ctx context.Context, limit int32) ([]MediaTranscodeJob, error)
	SetTranscodeJobStatus(ctx context.Context, arg SetTranscodeJobStatusParams) (MediaTranscodeJob, error)
	UpsertAudioAsset(ctx context.Context, arg UpsertAudioAssetParams) (uuid.UUID, error)
}

var _ Querier = (*Queries)(nil)
