// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBookIfSlugFree = `-- name: CreateBookIfSlugFree :one
INSERT INTO catalog.books (
    slug, title, author_id, description, cover_url, language,
    is_kids_friendly, status, published_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, now()
)
ON CONFLICT (slug) DO NOTHING
RETURNING id
`

type CreateBookIfSlugFreeParams struct {
	Slug           string      `json:"slug"`
	Title          string      `json:"title"`
	AuthorID       pgtype.UUID `json:"author_id"`
	Description    *string     `json:"description"`
	CoverUrl       *string     `json:"cover_url"`
	Language       string      `json:"language"`
	IsKidsFriendly bool        `json:"is_kids_friendly"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateBookIfSlugFree(ctx context.Context, arg CreateBookIfSlugFreeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createBookIfSlugFree,
		arg.Slug,
		arg.Title,
		arg.AuthorID,
		arg.Description,
		arg.CoverUrl,
		arg.Language,
		arg.IsKidsFriendly,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createChapter = `-- name: CreateChapter :exec
INSERT INTO catalog.chapters (audio_edition_id, title, sort_order, start_seconds, end_seconds)
VALUES ($1, $2, $3, $4, $5)
`

type CreateChapterParams struct {
	AudioEditionID uuid.UUID      `json:"audio_edition_id"`
	Title          string         `json:"title"`
	SortOrder      int32          `json:"sort_order"`
	StartSeconds   pgtype.Numeric `json:"start_seconds"`
	EndSeconds     pgtype.Numeric `json:"end_seconds"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) error {
	_, err := q.db.Exec(ctx, createChapter,
		arg.AudioEditionID,
		arg.Title,
		arg.SortOrder,
		arg.StartSeconds,
		arg.EndSeconds,
	)
	return err
}

const deleteChaptersForEdition = `-- name: DeleteChaptersForEdition :exec
DELETE FROM catalog.chapters WHERE audio_edition_id = $1
`

func (q *Queries) DeleteChaptersForEdition(ctx context.Context, audioEditionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChaptersForEdition, audioEditionID)
	return err
}

const ensureIngestRightsGrant = `-- name: EnsureIngestRightsGrant :exec
INSERT INTO catalog.rights_grants (book_id, scope, revenue_share_percent, contract_ref)
SELECT $1, 'audio_distribution', 0, 'ADMIN-PANEL-UPLOAD'
WHERE NOT EXISTS (SELECT 1 FROM catalog.rights_grants WHERE book_id = $1)
`

// HasActiveRights به‌طور پیش‌فرض «حق نداریم» برمی‌گرداند، پس کتابی که از
// پنل می‌آید بدون این ردیف برای هر بررسی مجوز نامرئی است. contract_ref
// عمداً می‌گوید منبعش پنل داخلی است، نه قراردادی که وجود ندارد.
func (q *Queries) EnsureIngestRightsGrant(ctx context.Context, bookID uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureIngestRightsGrant, bookID)
	return err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, bio, created_at, slug FROM catalog.authors WHERE id = $1
`

func (q *Queries) GetAuthorByID(ctx context.Context, id uuid.UUID) (CatalogAuthor, error) {
	row := q.db.QueryRow(ctx, getAuthorByID, id)
	var i CatalogAuthor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.Slug,
	)
	return i, err
}

const getAuthorBySlug = `-- name: GetAuthorBySlug :one
SELECT id, name, bio, created_at, slug FROM catalog.authors WHERE slug = $1
`

func (q *Queries) GetAuthorBySlug(ctx context.Context, slug string) (CatalogAuthor, error) {
	row := q.db.QueryRow(ctx, getAuthorBySlug, slug)
	var i CatalogAuthor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.Slug,
	)
	return i, err
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, slug, title, author_id, publisher_id, category_id, description, cover_url, language, is_kids_friendly, status, created_at, updated_at, subtitle, published_at, listen_count, rating_average, rating_count, search_document FROM catalog.books WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id uuid.UUID) (CatalogBook, error) {
	row := q.db.QueryRow(ctx, getBookByID, id)
	var i CatalogBook
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.AuthorID,
		&i.PublisherID,
		&i.CategoryID,
		&i.Description,
		&i.CoverUrl,
		&i.Language,
		&i.IsKidsFriendly,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subtitle,
		&i.PublishedAt,
		&i.ListenCount,
		&i.RatingAverage,
		&i.RatingCount,
		&i.SearchDocument,
	)
	return i, err
}

const getBookBySlug = `-- name: GetBookBySlug :one
SELECT id, slug, title, author_id, publisher_id, category_id, description, cover_url, language, is_kids_friendly, status, created_at, updated_at, subtitle, published_at, listen_count, rating_average, rating_count, search_document FROM catalog.books WHERE slug = $1
`

func (q *Queries) GetBookBySlug(ctx context.Context, slug string) (CatalogBook, error) {
	row := q.db.QueryRow(ctx, getBookBySlug, slug)
	var i CatalogBook
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.AuthorID,
		&i.PublisherID,
		&i.CategoryID,
		&i.Description,
		&i.CoverUrl,
		&i.Language,
		&i.IsKidsFriendly,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subtitle,
		&i.PublishedAt,
		&i.ListenCount,
		&i.RatingAverage,
		&i.RatingCount,
		&i.SearchDocument,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, parent_id FROM catalog.categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (CatalogCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i CatalogCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ParentID,
	)
	return i, err
}

const getPublisherBySlug = `-- name: GetPublisherBySlug :one
SELECT id, name, created_at, slug FROM catalog.publishers WHERE slug = $1
`

func (q *Queries) GetPublisherBySlug(ctx context.Context, slug string) (CatalogPublisher, error) {
	row := q.db.QueryRow(ctx, getPublisherBySlug, slug)
	var i CatalogPublisher
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Slug,
	)
	return i, err
}

const incrementListenCount = `-- name: IncrementListenCount :exec
UPDATE catalog.books SET listen_count = listen_count + $2 WHERE id = $1
`

type IncrementListenCountParams struct {
	ID          uuid.UUID `json:"id"`
	ListenCount int64     `json:"listen_count"`
}

func (q *Queries) IncrementListenCount(ctx context.Context, arg IncrementListenCountParams) error {
	_, err := q.db.Exec(ctx, incrementListenCount, arg.ID, arg.ListenCount)
	return err
}

const listBooks = `-- name: ListBooks :many
SELECT
    b.id, b.slug, b.title, b.author_id, b.publisher_id, b.category_id, b.description, b.cover_url, b.language, b.is_kids_friendly, b.status, b.created_at, b.updated_at, b.subtitle, b.published_at, b.listen_count, b.rating_average, b.rating_count, b.search_document,
    a.name AS author_name,
    a.slug AS author_slug,
    p.name AS publisher_name,
    c.name AS category_name,
    c.slug AS category_slug,
    count(*) OVER () AS total_count
FROM catalog.books b
LEFT JOIN catalog.authors a    ON a.id = b.author_id
LEFT JOIN catalog.publishers p ON p.id = b.publisher_id
LEFT JOIN catalog.categories c ON c.id = b.category_id
WHERE b.status = 'published'
  AND ($1::text IS NULL OR c.slug = $1::text)
  AND ($2::text   IS NULL OR a.slug = $2::text)
  AND ($3::text      IS NULL OR b.language = $3::text)
  AND ($4::boolean  IS NULL OR b.is_kids_friendly = $4::boolean)
ORDER BY
    CASE WHEN $5::text = 'popular' THEN b.listen_count END DESC NULLS LAST,
    CASE WHEN $5::text = 'rating'  THEN b.rating_average END DESC NULLS LAST,
    b.published_at DESC NULLS LAST,
    b.created_at DESC
LIMIT $7 OFFSET $6
`

type ListBooksParams struct {
	CategorySlug *string `json:"category_slug"`
	AuthorSlug   *string `json:"author_slug"`
	Language     *string `json:"language"`
	KidsOnly     *bool   `json:"kids_only"`
	Sort         string  `json:"sort"`
	PageOffset   int32   `json:"page_offset"`
	PageLimit    int32   `json:"page_limit"`
}

type ListBooksRow struct {
	ID             uuid.UUID          `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	PublisherID    pgtype.UUID        `json:"publisher_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	Description    *string            `json:"description"`
	CoverUrl       *string            `json:"cover_url"`
	Language       string             `json:"language"`
	IsKidsFriendly bool               `json:"is_kids_friendly"`
	Status         string             `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Subtitle       *string            `json:"subtitle"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	ListenCount    int64              `json:"listen_count"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	SearchDocument interface{}        `json:"search_document"`
	AuthorName     *string            `json:"author_name"`
	AuthorSlug     *string            `json:"author_slug"`
	PublisherName  *string            `json:"publisher_name"`
	CategoryName   *string            `json:"category_name"`
	CategorySlug   *string            `json:"category_slug"`
	TotalCount     int64              `json:"total_count"`
}

// ListBooks یک کوئری است نه پنج تا: هر فیلتر با الگوی
// «sqlc.narg IS NULL OR شرط» اختیاری می‌شود. دلیلش N+1 نیست، این است که
// صفحه کاتالوگ، صفحه دسته، صفحه نویسنده، صفحه کودک و نتیجه جستجو همه یک
// شکل داده برمی‌گردانند و باید یک جا مرتب و صفحه‌بندی شوند.
//
// kids_only فقط is_kids_friendly را چک می‌کند؛ سیاست کودکِ به‌ازای پروفایل
// (سن، تأیید والد) در ماژول kids اعمال می‌شود نه اینجا — کاتالوگ نمی‌داند
// کدام کودک درخواست داده.
func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]ListBooksRow, error) {
	rows, err := q.db.Query(ctx, listBooks,
		arg.CategorySlug,
		arg.AuthorSlug,
		arg.Language,
		arg.KidsOnly,
		arg.Sort,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksRow
	for rows.Next() {
		var i ListBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.AuthorID,
			&i.PublisherID,
			&i.CategoryID,
			&i.Description,
			&i.CoverUrl,
			&i.Language,
			&i.IsKidsFriendly,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subtitle,
			&i.PublishedAt,
			&i.ListenCount,
			&i.RatingAverage,
			&i.RatingCount,
			&i.SearchDocument,
			&i.AuthorName,
			&i.AuthorSlug,
			&i.PublisherName,
			&i.CategoryName,
			&i.CategorySlug,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooksInCollection = `-- name: ListBooksInCollection :many
SELECT b.id, b.slug, b.title, b.author_id, b.publisher_id, b.category_id, b.description, b.cover_url, b.language, b.is_kids_friendly, b.status, b.created_at, b.updated_at, b.subtitle, b.published_at, b.listen_count, b.rating_average, b.rating_count, b.search_document, a.name AS author_name, a.slug AS author_slug
FROM catalog.collection_books cb
JOIN catalog.books b ON b.id = cb.book_id AND b.status = 'published'
LEFT JOIN catalog.authors a ON a.id = b.author_id
WHERE cb.collection_id = $1
ORDER BY cb.sort_order
`

type ListBooksInCollectionRow struct {
	ID             uuid.UUID          `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	PublisherID    pgtype.UUID        `json:"publisher_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	Description    *string            `json:"description"`
	CoverUrl       *string            `json:"cover_url"`
	Language       string             `json:"language"`
	IsKidsFriendly bool               `json:"is_kids_friendly"`
	Status         string             `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Subtitle       *string            `json:"subtitle"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	ListenCount    int64              `json:"listen_count"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	SearchDocument interface{}        `json:"search_document"`
	AuthorName     *string            `json:"author_name"`
	AuthorSlug     *string            `json:"author_slug"`
}

func (q *Queries) ListBooksInCollection(ctx context.Context, collectionID uuid.UUID) ([]ListBooksInCollectionRow, error) {
	rows, err := q.db.Query(ctx, listBooksInCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBooksInCollectionRow
	for rows.Next() {
		var i ListBooksInCollectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.AuthorID,
			&i.PublisherID,
			&i.CategoryID,
			&i.Description,
			&i.CoverUrl,
			&i.Language,
			&i.IsKidsFriendly,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subtitle,
			&i.PublishedAt,
			&i.ListenCount,
			&i.RatingAverage,
			&i.RatingCount,
			&i.SearchDocument,
			&i.AuthorName,
			&i.AuthorSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.name, c.slug, c.parent_id, count(b.id) AS book_count
FROM catalog.categories c
LEFT JOIN catalog.books b ON b.category_id = c.id AND b.status = 'published'
GROUP BY c.id
ORDER BY c.name
`

type ListCategoriesRow struct {
	ID        uuid.UUID   `json:"id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	ParentID  pgtype.UUID `json:"parent_id"`
	BookCount int64       `json:"book_count"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ParentID,
			&i.BookCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollections = `-- name: ListCollections :many
SELECT id, name, slug, created_at FROM catalog.collections ORDER BY name
`

func (q *Queries) ListCollections(ctx context.Context) ([]CatalogCollection, error) {
	rows, err := q.db.Query(ctx, listCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogCollection
	for rows.Next() {
		var i CatalogCollection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooks = `-- name: SearchBooks :many
SELECT
    b.id, b.slug, b.title, b.author_id, b.publisher_id, b.category_id, b.description, b.cover_url, b.language, b.is_kids_friendly, b.status, b.created_at, b.updated_at, b.subtitle, b.published_at, b.listen_count, b.rating_average, b.rating_count, b.search_document,
    a.name AS author_name,
    a.slug AS author_slug,
    ts_rank(b.search_document, plainto_tsquery('simple', catalog.normalize_fa($1::text))) AS text_rank,
    similarity(catalog.normalize_fa(b.title), catalog.normalize_fa($1::text)) AS title_similarity,
    count(*) OVER () AS total_count
FROM catalog.books b
LEFT JOIN catalog.authors a ON a.id = b.author_id
WHERE b.status = 'published'
  AND ($2::boolean IS NULL OR b.is_kids_friendly = $2::boolean)
  AND (
        b.search_document @@ plainto_tsquery('simple', catalog.normalize_fa($1::text))
     -- The trigram arm catches what FTS cannot: a misspelling, or a
     -- prefix of a compound word ("قصه" against "قصه‌های"), which after
     -- normalization is a substring rather than a token match.
     OR catalog.normalize_fa(b.title) % catalog.normalize_fa($1::text)
     OR catalog.normalize_fa(b.title) ILIKE '%' || catalog.normalize_fa($1::text) || '%'
     OR catalog.normalize_fa(a.name)  % catalog.normalize_fa($1::text)
  )
ORDER BY
    ts_rank(b.search_document, plainto_tsquery('simple', catalog.normalize_fa($1::text))) DESC,
    similarity(catalog.normalize_fa(b.title), catalog.normalize_fa($1::text)) DESC,
    b.listen_count DESC
LIMIT $4 OFFSET $3
`

type SearchBooksParams struct {
	Query      string `json:"query"`
	KidsOnly   *bool  `json:"kids_only"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

type SearchBooksRow struct {
	ID              uuid.UUID          `json:"id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	PublisherID     pgtype.UUID        `json:"publisher_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Description     *string            `json:"description"`
	CoverUrl        *string            `json:"cover_url"`
	Language        string             `json:"language"`
	IsKidsFriendly  bool               `json:"is_kids_friendly"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	Subtitle        *string            `json:"subtitle"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ListenCount     int64              `json:"listen_count"`
	RatingAverage   pgtype.Numeric     `json:"rating_average"`
	RatingCount     int32              `json:"rating_count"`
	SearchDocument  interface{}        `json:"search_document"`
	AuthorName      *string            `json:"author_name"`
	AuthorSlug      *string            `json:"author_slug"`
	TextRank        float32            `json:"text_rank"`
	TitleSimilarity float32            `json:"title_similarity"`
	TotalCount      int64              `json:"total_count"`
}

// SearchBooks دو سیگنال را با هم می‌گیرد: FTS برای واژه کامل و
// similarity/trigram برای غلط املایی. املای فارسی («طهران/تهران»،
// نیم‌فاصله، «ی» عربی و فارسی) بدون trigram نتیجه صفر می‌دهد و کاربر فکر
// می‌کند کتاب را نداریم. تا ده هزار عنوان همین کافی است؛ عبور از آن یعنی
// وقت Meilisearch است (08-decisions.md).
func (q *Queries) SearchBooks(ctx context.Context, arg SearchBooksParams) ([]SearchBooksRow, error) {
	rows, err := q.db.Query(ctx, searchBooks,
		arg.Query,
		arg.KidsOnly,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBooksRow
	for rows.Next() {
		var i SearchBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.AuthorID,
			&i.PublisherID,
			&i.CategoryID,
			&i.Description,
			&i.CoverUrl,
			&i.Language,
			&i.IsKidsFriendly,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subtitle,
			&i.PublishedAt,
			&i.ListenCount,
			&i.RatingAverage,
			&i.RatingCount,
			&i.SearchDocument,
			&i.AuthorName,
			&i.AuthorSlug,
			&i.TextRank,
			&i.TitleSimilarity,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBookCoverURL = `-- name: SetBookCoverURL :exec
UPDATE catalog.books SET cover_url = $1, updated_at = now() WHERE id = $2
`

type SetBookCoverURLParams struct {
	CoverUrl *string   `json:"cover_url"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) SetBookCoverURL(ctx context.Context, arg SetBookCoverURLParams) error {
	_, err := q.db.Exec(ctx, setBookCoverURL, arg.CoverUrl, arg.ID)
	return err
}

const setBookDescriptionIfEmpty = `-- name: SetBookDescriptionIfEmpty :exec
UPDATE catalog.books
SET description = $1, updated_at = now()
WHERE id = $2 AND (description IS NULL OR description = '')
`

type SetBookDescriptionIfEmptyParams struct {
	Description *string   `json:"description"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) SetBookDescriptionIfEmpty(ctx context.Context, arg SetBookDescriptionIfEmptyParams) error {
	_, err := q.db.Exec(ctx, setBookDescriptionIfEmpty, arg.Description, arg.ID)
	return err
}

const upsertAIEdition = `-- name: UpsertAIEdition :one
INSERT INTO catalog.audio_editions (
    book_id, voice_id, narrator_type, language, is_kids_friendly,
    price_irr, preview_seconds, duration_seconds, status, published_at
) VALUES (
    $1, $2, 'ai', $3, $4,
    $5, $6, $7, 'published', now()
)
ON CONFLICT (book_id, voice_id) DO UPDATE
SET duration_seconds = EXCLUDED.duration_seconds,
    status           = 'published',
    published_at     = coalesce(catalog.audio_editions.published_at, now())
RETURNING id
`

type UpsertAIEditionParams struct {
	BookID          uuid.UUID `json:"book_id"`
	VoiceID         string    `json:"voice_id"`
	Language        string    `json:"language"`
	IsKidsFriendly  bool      `json:"is_kids_friendly"`
	PriceIrr        int64     `json:"price_irr"`
	PreviewSeconds  int32     `json:"preview_seconds"`
	DurationSeconds int32     `json:"duration_seconds"`
}

func (q *Queries) UpsertAIEdition(ctx context.Context, arg UpsertAIEditionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAIEdition,
		arg.BookID,
		arg.VoiceID,
		arg.Language,
		arg.IsKidsFriendly,
		arg.PriceIrr,
		arg.PreviewSeconds,
		arg.DurationSeconds,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertAuthorByName = `-- name: UpsertAuthorByName :one

INSERT INTO catalog.authors (name, slug)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, bio, created_at, slug
`

type UpsertAuthorByNameParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// نوشتن در کاتالوگ از مسیر پنل تولید محتوا.
//
// این کوئری‌ها اینجا هستند نه در ماژول ingest، چون قاعده معماری این است
// که هر ماژول تنها نویسنده جدول‌های خودش باشد. ingest تراکنش خودش را
// می‌دهد (CreateBookInTx) تا ردیف کاتالوگ، ردیف سرویس AI و job همگی با
// هم commit شوند، ولی SQL آن همین‌جا می‌ماند.
func (q *Queries) UpsertAuthorByName(ctx context.Context, arg UpsertAuthorByNameParams) (CatalogAuthor, error) {
	row := q.db.QueryRow(ctx, upsertAuthorByName, arg.Name, arg.Slug)
	var i CatalogAuthor
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.Slug,
	)
	return i, err
}

const upsertVoice = `-- name: UpsertVoice :one
INSERT INTO catalog.voices (id, name, style, is_default, is_kids, sort_order)
VALUES ($1, $2, $3, false, false, 0)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name, style, is_default, is_kids, sort_order, created_at
`

type UpsertVoiceParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Style string `json:"style"`
}

// نسخه صوتی تولیدشده با TTS.
//
// گوینده upsert می‌شود چون قرارداد شناسه صدا (voices.id == sources[].voiceId)
// می‌گوید این شناسه در کل سیستم یکی است؛ دیتابیسی که seed نشده هم باید بتواند
// اولین کتاب TTS شده را بپذیرد بدون اینکه FK بشکند.
func (q *Queries) UpsertVoice(ctx context.Context, arg UpsertVoiceParams) (CatalogVoice, error) {
	row := q.db.QueryRow(ctx, upsertVoice, arg.ID, arg.Name, arg.Style)
	var i CatalogVoice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Style,
		&i.IsDefault,
		&i.IsKids,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
