// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: editions.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getEditionByID = `-- name: GetEditionByID :one
SELECT
    ae.id AS audio_edition_id,
    ae.book_id,
    ae.voice_id,
    v.name AS voice_name,
    v.style AS voice_style,
    ae.is_kids_friendly,
    ae.narrator_type,
    ae.dialect,
    ae.language,
    ae.price_irr,
    ae.preview_seconds,
    ae.duration_seconds,
    ae.status
FROM catalog.audio_editions ae
JOIN catalog.voices v ON v.id = ae.voice_id
WHERE ae.id = $1
`

type GetEditionByIDRow struct {
	AudioEditionID  uuid.UUID `json:"audio_edition_id"`
	BookID          uuid.UUID `json:"book_id"`
	VoiceID         string    `json:"voice_id"`
	VoiceName       string    `json:"voice_name"`
	VoiceStyle      string    `json:"voice_style"`
	IsKidsFriendly  bool      `json:"is_kids_friendly"`
	NarratorType    string    `json:"narrator_type"`
	Dialect         *string   `json:"dialect"`
	Language        string    `json:"language"`
	PriceIrr        int64     `json:"price_irr"`
	PreviewSeconds  int32     `json:"preview_seconds"`
	DurationSeconds int32     `json:"duration_seconds"`
	Status          string    `json:"status"`
}

func (q *Queries) GetEditionByID(ctx context.Context, id uuid.UUID) (GetEditionByIDRow, error) {
	row := q.db.QueryRow(ctx, getEditionByID, id)
	var i GetEditionByIDRow
	err := row.Scan(
		&i.AudioEditionID,
		&i.BookID,
		&i.VoiceID,
		&i.VoiceName,
		&i.VoiceStyle,
		&i.IsKidsFriendly,
		&i.NarratorType,
		&i.Dialect,
		&i.Language,
		&i.PriceIrr,
		&i.PreviewSeconds,
		&i.DurationSeconds,
		&i.Status,
	)
	return i, err
}

const getTranscriptForEdition = `-- name: GetTranscriptForEdition :one
SELECT id, audio_edition_id, language, content, created_at FROM catalog.transcripts WHERE audio_edition_id = $1
`

func (q *Queries) GetTranscriptForEdition(ctx context.Context, audioEditionID uuid.UUID) (CatalogTranscript, error) {
	row := q.db.QueryRow(ctx, getTranscriptForEdition, audioEditionID)
	var i CatalogTranscript
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.Language,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getTranscriptSegmentsInRange = `-- name: GetTranscriptSegmentsInRange :many
SELECT
    (segment->>'text')::text          AS text,
    (segment->>'startSeconds')::numeric AS start_seconds,
    (segment->>'endSeconds')::numeric   AS end_seconds
FROM catalog.transcripts t,
     jsonb_array_elements(t.content) AS segment
WHERE t.audio_edition_id = $1
  AND (segment->>'endSeconds')::numeric   >= $2::numeric
  AND (segment->>'startSeconds')::numeric <= $3::numeric
ORDER BY (segment->>'startSeconds')::numeric
`

type GetTranscriptSegmentsInRangeParams struct {
	AudioEditionID uuid.UUID      `json:"audio_edition_id"`
	FromSeconds    pgtype.Numeric `json:"from_seconds"`
	ToSeconds      pgtype.Numeric `json:"to_seconds"`
}

type GetTranscriptSegmentsInRangeRow struct {
	Text         string         `json:"text"`
	StartSeconds pgtype.Numeric `json:"start_seconds"`
	EndSeconds   pgtype.Numeric `json:"end_seconds"`
}

// ترنسکریپت را برش‌خورده هم لازم داریم: کتاب‌یار فقط قطعات نزدیک به
// موقعیت فعلی را به‌عنوان context می‌خواهد، نه کل کتاب را. jsonb_array_elements
// اینجا کار می‌کند چون content آرایه {text,startSeconds,endSeconds} است.
func (q *Queries) GetTranscriptSegmentsInRange(ctx context.Context, arg GetTranscriptSegmentsInRangeParams) ([]GetTranscriptSegmentsInRangeRow, error) {
	rows, err := q.db.Query(ctx, getTranscriptSegmentsInRange, arg.AudioEditionID, arg.FromSeconds, arg.ToSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTranscriptSegmentsInRangeRow
	for rows.Next() {
		var i GetTranscriptSegmentsInRangeRow
		if err := rows.Scan(&i.Text, &i.StartSeconds, &i.EndSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChaptersForEdition = `-- name: ListChaptersForEdition :many
SELECT id, audio_edition_id, title, sort_order, start_seconds, end_seconds FROM catalog.chapters
WHERE audio_edition_id = $1
ORDER BY sort_order
`

func (q *Queries) ListChaptersForEdition(ctx context.Context, audioEditionID uuid.UUID) ([]CatalogChapter, error) {
	rows, err := q.db.Query(ctx, listChaptersForEdition, audioEditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogChapter
	for rows.Next() {
		var i CatalogChapter
		if err := rows.Scan(
			&i.ID,
			&i.AudioEditionID,
			&i.Title,
			&i.SortOrder,
			&i.StartSeconds,
			&i.EndSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditionsForBook = `-- name: ListEditionsForBook :many
SELECT
    ae.id AS audio_edition_id,
    ae.book_id,
    ae.voice_id,
    v.name AS voice_name,
    v.style AS voice_style,
    ae.is_kids_friendly,
    ae.narrator_type,
    ae.dialect,
    ae.language,
    ae.price_irr,
    ae.preview_seconds,
    ae.duration_seconds
FROM catalog.audio_editions ae
JOIN catalog.voices v ON v.id = ae.voice_id
WHERE ae.book_id = $1 AND ae.status = 'published'
ORDER BY v.sort_order
`

type ListEditionsForBookRow struct {
	AudioEditionID  uuid.UUID `json:"audio_edition_id"`
	BookID          uuid.UUID `json:"book_id"`
	VoiceID         string    `json:"voice_id"`
	VoiceName       string    `json:"voice_name"`
	VoiceStyle      string    `json:"voice_style"`
	IsKidsFriendly  bool      `json:"is_kids_friendly"`
	NarratorType    string    `json:"narrator_type"`
	Dialect         *string   `json:"dialect"`
	Language        string    `json:"language"`
	PriceIrr        int64     `json:"price_irr"`
	PreviewSeconds  int32     `json:"preview_seconds"`
	DurationSeconds int32     `json:"duration_seconds"`
}

func (q *Queries) ListEditionsForBook(ctx context.Context, bookID uuid.UUID) ([]ListEditionsForBookRow, error) {
	rows, err := q.db.Query(ctx, listEditionsForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEditionsForBookRow
	for rows.Next() {
		var i ListEditionsForBookRow
		if err := rows.Scan(
			&i.AudioEditionID,
			&i.BookID,
			&i.VoiceID,
			&i.VoiceName,
			&i.VoiceStyle,
			&i.IsKidsFriendly,
			&i.NarratorType,
			&i.Dialect,
			&i.Language,
			&i.PriceIrr,
			&i.PreviewSeconds,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEditionDuration = `-- name: SetEditionDuration :exec
UPDATE catalog.audio_editions SET duration_seconds = $2 WHERE id = $1
`

type SetEditionDurationParams struct {
	ID              uuid.UUID `json:"id"`
	DurationSeconds int32     `json:"duration_seconds"`
}

func (q *Queries) SetEditionDuration(ctx context.Context, arg SetEditionDurationParams) error {
	_, err := q.db.Exec(ctx, setEditionDuration, arg.ID, arg.DurationSeconds)
	return err
}

const upsertTranscript = `-- name: UpsertTranscript :one
INSERT INTO catalog.transcripts (audio_edition_id, language, content)
VALUES ($1, $2, $3)
ON CONFLICT (audio_edition_id) DO UPDATE
SET content = EXCLUDED.content, language = EXCLUDED.language
RETURNING id, audio_edition_id, language, content, created_at
`

type UpsertTranscriptParams struct {
	AudioEditionID uuid.UUID `json:"audio_edition_id"`
	Language       string    `json:"language"`
	Content        []byte    `json:"content"`
}

func (q *Queries) UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (CatalogTranscript, error) {
	row := q.db.QueryRow(ctx, upsertTranscript, arg.AudioEditionID, arg.Language, arg.Content)
	var i CatalogTranscript
	err := row.Scan(
		&i.ID,
		&i.AudioEditionID,
		&i.Language,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
