// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lexicon.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const hasActiveRights = `-- name: HasActiveRights :one
SELECT EXISTS (
    SELECT 1 FROM catalog.rights_grants
    WHERE book_id = $1
      AND starts_at <= now()
      AND (expires_at IS NULL OR expires_at > now())
) AS has_rights
`

// HasActiveRights پاسخ به سؤال «آیا حق پخش این کتاب را داریم». اگر هیچ
// RightsGrant ثبت نشده باشد نتیجه false است — پیش‌فرض «حق نداریم»، نه
// «حق داریم». این تفاوت، تفاوت میان یک پرونده حقوقی و یک صف بازبینی است.
func (q *Queries) HasActiveRights(ctx context.Context, bookID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveRights, bookID)
	var has_rights bool
	err := row.Scan(&has_rights)
	return has_rights, err
}

const listRightsGrantsForBook = `-- name: ListRightsGrantsForBook :many
SELECT id, book_id, publisher_id, scope, revenue_share_percent, starts_at, expires_at, contract_ref, created_at FROM catalog.rights_grants
WHERE book_id = $1
ORDER BY starts_at DESC
`

func (q *Queries) ListRightsGrantsForBook(ctx context.Context, bookID uuid.UUID) ([]CatalogRightsGrant, error) {
	rows, err := q.db.Query(ctx, listRightsGrantsForBook, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogRightsGrant
	for rows.Next() {
		var i CatalogRightsGrant
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.PublisherID,
			&i.Scope,
			&i.RevenueSharePercent,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ContractRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveLexicon = `-- name: ResolveLexicon :many
SELECT DISTINCT ON (grapheme)
    grapheme, phoneme, book_id
FROM catalog.pronunciation_lexicon
WHERE language = $1::text
  AND (book_id IS NULL OR book_id = $2::uuid)
ORDER BY grapheme, book_id NULLS LAST
`

type ResolveLexiconParams struct {
	Language string      `json:"language"`
	BookID   pgtype.UUID `json:"book_id"`
}

type ResolveLexiconRow struct {
	Grapheme string      `json:"grapheme"`
	Phoneme  string      `json:"phoneme"`
	BookID   pgtype.UUID `json:"book_id"`
}

// ResolveLexicon کل واژه‌نامه مؤثر برای یک کتاب را می‌دهد: ورودی مخصوص
// کتاب بر ورودی سراسری مقدم است، چون «کرم» در یک کتاب زیست‌شناسی و یک
// کتاب اخلاق دو تلفظ متفاوت دارد.
func (q *Queries) ResolveLexicon(ctx context.Context, arg ResolveLexiconParams) ([]ResolveLexiconRow, error) {
	rows, err := q.db.Query(ctx, resolveLexicon, arg.Language, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResolveLexiconRow
	for rows.Next() {
		var i ResolveLexiconRow
		if err := rows.Scan(&i.Grapheme, &i.Phoneme, &i.BookID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLexiconEntry = `-- name: UpsertLexiconEntry :one
INSERT INTO catalog.pronunciation_lexicon (book_id, grapheme, phoneme, language, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING id, book_id, grapheme, phoneme, language, created_by, created_at
`

type UpsertLexiconEntryParams struct {
	BookID    pgtype.UUID `json:"book_id"`
	Grapheme  string      `json:"grapheme"`
	Phoneme   string      `json:"phoneme"`
	Language  string      `json:"language"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) UpsertLexiconEntry(ctx context.Context, arg UpsertLexiconEntryParams) (CatalogPronunciationLexicon, error) {
	row := q.db.QueryRow(ctx, upsertLexiconEntry,
		arg.BookID,
		arg.Grapheme,
		arg.Phoneme,
		arg.Language,
		arg.CreatedBy,
	)
	var i CatalogPronunciationLexicon
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Grapheme,
		&i.Phoneme,
		&i.Language,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
