// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateBookIfSlugFree(ctx context.Context, arg CreateBookIfSlugFreeParams) (uuid.UUID, error)
	CreateChapter(ctx context.Context, arg CreateChapterParams) error
	DeleteChaptersForEdition(ctx context.Context, audioEditionID uuid.UUID) error
	// HasActiveRights به‌طور پیش‌فرض «حق نداریم» برمی‌گرداند، پس کتابی که از
	// پنل می‌آید بدون این ردیف برای هر بررسی مجوز نامرئی است. contract_ref
	// عمداً می‌گوید منبعش پنل داخلی است، نه قراردادی که وجود ندارد.
	EnsureIngestRightsGrant(ctx context.Context, bookID uuid.UUID) error
	GetAuthorByID(ctx context.Context, id uuid.UUID) (CatalogAuthor, error)
	GetAuthorBySlug(ctx context.Context, slug string) (CatalogAuthor, error)
	GetBookByID(ctx context.Context, id uuid.UUID) (CatalogBook, error)
	GetBookBySlug(ctx context.Context, slug string) (CatalogBook, error)
	GetCategoryBySlug(ctx context.Context, slug string) (CatalogCategory, error)
	GetEditionByID(ctx context.Context, id uuid.UUID) (GetEditionByIDRow, error)
	GetPublisherBySlug(ctx context.Context, slug string) (CatalogPublisher, error)
	GetTranscriptForEdition(ctx context.Context, audioEditionID uuid.UUID) (CatalogTranscript, error)
	// ترنسکریپت را برش‌خورده هم لازم داریم: کتاب‌یار فقط قطعات نزدیک به
	// موقعیت فعلی را به‌عنوان context می‌خواهد، نه کل کتاب را. jsonb_array_elements
	// اینجا کار می‌کند چون content آرایه {text,startSeconds,endSeconds} است.
	GetTranscriptSegmentsInRange(ctx context.Context, arg GetTranscriptSegmentsInRangeParams) ([]GetTranscriptSegmentsInRangeRow, error)
	GetVoiceByID(ctx context.Context, id string) (CatalogVoice, error)
	// HasActiveRights پاسخ به سؤال «آیا حق پخش این کتاب را داریم». اگر هیچ
	// RightsGrant ثبت نشده باشد نتیجه false است — پیش‌فرض «حق نداریم»، نه
	// «حق داریم». این تفاوت، تفاوت میان یک پرونده حقوقی و یک صف بازبینی است.
	HasActiveRights(ctx context.Context, bookID uuid.UUID) (bool, error)
	IncrementListenCount(ctx context.Context, arg IncrementListenCountParams) error
	// ListBooks یک کوئری است نه پنج تا: هر فیلتر با الگوی
	// «sqlc.narg IS NULL OR شرط» اختیاری می‌شود. دلیلش N+1 نیست، این است که
	// صفحه کاتالوگ، صفحه دسته، صفحه نویسنده، صفحه کودک و نتیجه جستجو همه یک
	// شکل داده برمی‌گردانند و باید یک جا مرتب و صفحه‌بندی شوند.
	//
	// kids_only فقط is_kids_friendly را چک می‌کند؛ سیاست کودکِ به‌ازای پروفایل
	// (سن، تأیید والد) در ماژول kids اعمال می‌شود نه اینجا — کاتالوگ نمی‌داند
	// کدام کودک درخواست داده.
	ListBooks(ctx context.Context, arg ListBooksParams) ([]ListBooksRow, error)
	ListBooksInCollection(ctx context.Context, collectionID uuid.UUID) ([]ListBooksInCollectionRow, error)
	ListCategories(ctx context.Context) ([]ListCategoriesRow, error)
	ListChaptersForEdition(ctx context.Context, audioEditionID uuid.UUID) ([]CatalogChapter, error)
	ListCollections(ctx context.Context) ([]CatalogCollection, error)
	ListEditionsForBook(ctx context.Context, bookID uuid.UUID) ([]ListEditionsForBookRow, error)
	ListRightsGrantsForBook(ctx context.Context, bookID uuid.UUID) ([]CatalogRightsGrant, error)
	ListVoices(ctx context.Context) ([]CatalogVoice, error)
	// ResolveLexicon کل واژه‌نامه مؤثر برای یک کتاب را می‌دهد: ورودی مخصوص
	// کتاب بر ورودی سراسری مقدم است، چون «کرم» در یک کتاب زیست‌شناسی و یک
	// کتاب اخلاق دو تلفظ متفاوت دارد.
	ResolveLexicon(ctx context.Context, arg ResolveLexiconParams) ([]ResolveLexiconRow, error)
	// SearchBooks دو سیگنال را با هم می‌گیرد: FTS برای واژه کامل و
	// similarity/trigram برای غلط املایی. املای فارسی («طهران/تهران»،
	// نیم‌فاصله، «ی» عربی و فارسی) بدون trigram نتیجه صفر می‌دهد و کاربر فکر
	// می‌کند کتاب را نداریم. تا ده هزار عنوان همین کافی است؛ عبور از آن یعنی
	// وقت Meilisearch است (08-decisions.md).
	SearchBooks(ctx context.Context, arg SearchBooksParams) ([]SearchBooksRow, error)
	SetBookCoverURL(ctx context.Context, arg SetBookCoverURLParams) error
	SetBookDescriptionIfEmpty(ctx context.Context, arg SetBookDescriptionIfEmptyParams) error
	SetEditionDuration(ctx context.Context, arg SetEditionDurationParams) error
	UpsertAIEdition(ctx context.Context, arg UpsertAIEditionParams) (uuid.UUID, error)
	// نوشتن در کاتالوگ از مسیر پنل تولید محتوا.
	//
	// این کوئری‌ها اینجا هستند نه در ماژول ingest، چون قاعده معماری این است
	// که هر ماژول تنها نویسنده جدول‌های خودش باشد. ingest تراکنش خودش را
	// می‌دهد (CreateBookInTx) تا ردیف کاتالوگ، ردیف سرویس AI و job همگی با
	// هم commit شوند، ولی SQL آن همین‌جا می‌ماند.
	UpsertAuthorByName(ctx context.Context, arg UpsertAuthorByNameParams) (CatalogAuthor, error)
	UpsertLexiconEntry(ctx context.Context, arg UpsertLexiconEntryParams) (CatalogPronunciationLexicon, error)
	UpsertTranscript(ctx context.Context, arg UpsertTranscriptParams) (CatalogTranscript, error)
	// نسخه صوتی تولیدشده با TTS.
	//
	// گوینده upsert می‌شود چون قرارداد شناسه صدا (voices.id == sources[].voiceId)
	// می‌گوید این شناسه در کل سیستم یکی است؛ دیتابیسی که seed نشده هم باید بتواند
	// اولین کتاب TTS شده را بپذیرد بدون اینکه FK بشکند.
	UpsertVoice(ctx context.Context, arg UpsertVoiceParams) (CatalogVoice, error)
}

var _ Querier = (*Queries)(nil)
