// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: voices.sql

package sqlcgen

import (
	"context"
)

const getVoiceByID = `-- name: GetVoiceByID :one
SELECT id, name, style, is_default, is_kids, sort_order, created_at FROM catalog.voices WHERE id = $1
`

func (q *Queries) GetVoiceByID(ctx context.Context, id string) (CatalogVoice, error) {
	row := q.db.QueryRow(ctx, getVoiceByID, id)
	var i CatalogVoice
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Style,
		&i.IsDefault,
		&i.IsKids,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listVoices = `-- name: ListVoices :many
SELECT id, name, style, is_default, is_kids, sort_order, created_at FROM catalog.voices ORDER BY sort_order, id
`

func (q *Queries) ListVoices(ctx context.Context) ([]CatalogVoice, error) {
	rows, err := q.db.Query(ctx, listVoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogVoice
	for rows.Next() {
		var i CatalogVoice
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Style,
			&i.IsDefault,
			&i.IsKids,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
