// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entitlements.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEntitlement = `-- name: CreateEntitlement :one
INSERT INTO commerce.entitlements (user_id, book_id, audio_edition_id, origin, source_reference_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, book_id, audio_edition_id, origin, source_reference_id, granted_at, expires_at, revoked_at
`

type CreateEntitlementParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	BookID            pgtype.UUID        `json:"book_id"`
	AudioEditionID    pgtype.UUID        `json:"audio_edition_id"`
	Origin            string             `json:"origin"`
	SourceReferenceID pgtype.UUID        `json:"source_reference_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (CommerceEntitlement, error) {
	row := q.db.QueryRow(ctx, createEntitlement,
		arg.UserID,
		arg.BookID,
		arg.AudioEditionID,
		arg.Origin,
		arg.SourceReferenceID,
		arg.ExpiresAt,
	)
	var i CommerceEntitlement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.AudioEditionID,
		&i.Origin,
		&i.SourceReferenceID,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const grantEntitlementIdempotent = `-- name: GrantEntitlementIdempotent :one
INSERT INTO commerce.entitlements (user_id, book_id, audio_edition_id, origin, source_reference_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, audio_edition_id, origin) WHERE revoked_at IS NULL AND audio_edition_id IS NOT NULL
DO UPDATE SET expires_at = EXCLUDED.expires_at
RETURNING id, user_id, book_id, audio_edition_id, origin, source_reference_id, granted_at, expires_at, revoked_at
`

type GrantEntitlementIdempotentParams struct {
	UserID            uuid.UUID          `json:"user_id"`
	BookID            pgtype.UUID        `json:"book_id"`
	AudioEditionID    pgtype.UUID        `json:"audio_edition_id"`
	Origin            string             `json:"origin"`
	SourceReferenceID pgtype.UUID        `json:"source_reference_id"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

// خرید دو بار همان نسخه نباید دو ردیف بسازد. ON CONFLICT روی همان
// ایندکس جزئی یکتای مهاجرت 00008 می‌نشیند، پس دو کلیک هم‌زمان «خرید»
// به یک entitlement می‌رسند نه دو تا.
func (q *Queries) GrantEntitlementIdempotent(ctx context.Context, arg GrantEntitlementIdempotentParams) (CommerceEntitlement, error) {
	row := q.db.QueryRow(ctx, grantEntitlementIdempotent,
		arg.UserID,
		arg.BookID,
		arg.AudioEditionID,
		arg.Origin,
		arg.SourceReferenceID,
		arg.ExpiresAt,
	)
	var i CommerceEntitlement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BookID,
		&i.AudioEditionID,
		&i.Origin,
		&i.SourceReferenceID,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const isUserEntitledToBook = `-- name: IsUserEntitledToBook :one
SELECT EXISTS (
    SELECT 1 FROM commerce.entitlements
    WHERE user_id = $1
      AND book_id = $2
      AND revoked_at IS NULL
      AND (expires_at IS NULL OR expires_at > now())
) AS entitled
`

type IsUserEntitledToBookParams struct {
	UserID uuid.UUID   `json:"user_id"`
	BookID pgtype.UUID `json:"book_id"`
}

func (q *Queries) IsUserEntitledToBook(ctx context.Context, arg IsUserEntitledToBookParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserEntitledToBook, arg.UserID, arg.BookID)
	var entitled bool
	err := row.Scan(&entitled)
	return entitled, err
}

const isUserEntitledToEdition = `-- name: IsUserEntitledToEdition :one
SELECT EXISTS (
    SELECT 1 FROM commerce.entitlements
    WHERE user_id = $1
      AND revoked_at IS NULL
      AND (expires_at IS NULL OR expires_at > now())
      AND (audio_edition_id = $2 OR (audio_edition_id IS NULL AND book_id = $3))
) AS entitled
`

type IsUserEntitledToEditionParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	AudioEditionID pgtype.UUID `json:"audio_edition_id"`
	BookID         pgtype.UUID `json:"book_id"`
}

// دسترسی در سطح AudioEdition سنجیده می‌شود نه فقط Book: خرید نسخه
// «آرام» حق پخش نسخه «نمایشی» را نمی‌دهد چون قیمتشان مستقل است. اما
// entitlement با audio_edition_id تهی (اشتراک، دسترسی سازمانی) کل کتاب
// را پوشش می‌دهد.
func (q *Queries) IsUserEntitledToEdition(ctx context.Context, arg IsUserEntitledToEditionParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserEntitledToEdition, arg.UserID, arg.AudioEditionID, arg.BookID)
	var entitled bool
	err := row.Scan(&entitled)
	return entitled, err
}

const listActiveEntitlementsForUser = `-- name: ListActiveEntitlementsForUser :many
SELECT id, user_id, book_id, audio_edition_id, origin, source_reference_id, granted_at, expires_at, revoked_at FROM commerce.entitlements
WHERE user_id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
ORDER BY granted_at DESC
`

func (q *Queries) ListActiveEntitlementsForUser(ctx context.Context, userID uuid.UUID) ([]CommerceEntitlement, error) {
	rows, err := q.db.Query(ctx, listActiveEntitlementsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceEntitlement
	for rows.Next() {
		var i CommerceEntitlement
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BookID,
			&i.AudioEditionID,
			&i.Origin,
			&i.SourceReferenceID,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeEntitlement = `-- name: RevokeEntitlement :exec
UPDATE commerce.entitlements
SET revoked_at = now()
WHERE id = $1
`

func (q *Queries) RevokeEntitlement(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeEntitlement, id)
	return err
}

const revokeEntitlementsForOrder = `-- name: RevokeEntitlementsForOrder :exec
UPDATE commerce.entitlements
SET revoked_at = now()
WHERE source_reference_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeEntitlementsForOrder(ctx context.Context, sourceReferenceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeEntitlementsForOrder, sourceReferenceID)
	return err
}
