// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AlembicVersion struct {
	VersionNum string `json:"version_num"`
}

type AudioAsset struct {
	ID         uuid.UUID   `json:"id"`
	BookID     uuid.UUID   `json:"book_id"`
	ChapterID  pgtype.UUID `json:"chapter_id"`
	SectionID  pgtype.UUID `json:"section_id"`
	StorageKey string      `json:"storage_key"`
	Format     string      `json:"format"`
	Duration   *float64    `json:"duration"`
	Status     string      `json:"status"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type Book struct {
	ID              uuid.UUID   `json:"id"`
	Title           string      `json:"title"`
	Author          *string     `json:"author"`
	Description     *string     `json:"description"`
	Publisher       *string     `json:"publisher"`
	PublicationYear *int32      `json:"publication_year"`
	Language        string      `json:"language"`
	Status          interface{} `json:"status"`
	Cover           *string     `json:"cover"`
	Categories      []string    `json:"categories"`
	Metadata        []byte      `json:"metadata"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
}

type BookChapter struct {
	ID         uuid.UUID `json:"id"`
	BookID     uuid.UUID `json:"book_id"`
	Title      string    `json:"title"`
	OrderIndex int32     `json:"order_index"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type BookChunk struct {
	ID         uuid.UUID   `json:"id"`
	BookID     uuid.UUID   `json:"book_id"`
	ChapterID  pgtype.UUID `json:"chapter_id"`
	SectionID  pgtype.UUID `json:"section_id"`
	Content    string      `json:"content"`
	ChunkIndex int32       `json:"chunk_index"`
	PageNumber *int32      `json:"page_number"`
	Language   string      `json:"language"`
	SourceType *string     `json:"source_type"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type BookDocument struct {
	ID           uuid.UUID   `json:"id"`
	BookID       uuid.UUID   `json:"book_id"`
	FileName     string      `json:"file_name"`
	StorageKey   string      `json:"storage_key"`
	MimeType     string      `json:"mime_type"`
	Size         int32       `json:"size"`
	DocumentType interface{} `json:"document_type"`
	Status       interface{} `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type BookSection struct {
	ID         uuid.UUID `json:"id"`
	ChapterID  uuid.UUID `json:"chapter_id"`
	Title      string    `json:"title"`
	OrderIndex int32     `json:"order_index"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type CatalogAudioEdition struct {
	ID              uuid.UUID          `json:"id"`
	BookID          uuid.UUID          `json:"book_id"`
	VoiceID         string             `json:"voice_id"`
	NarratorType    string             `json:"narrator_type"`
	Dialect         *string            `json:"dialect"`
	Language        string             `json:"language"`
	IsKidsFriendly  bool               `json:"is_kids_friendly"`
	PriceIrr        int64              `json:"price_irr"`
	Status          string             `json:"status"`
	CreatedAt       time.Time          `json:"created_at"`
	PreviewSeconds  int32              `json:"preview_seconds"`
	DurationSeconds int32              `json:"duration_seconds"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

type CatalogAuthor struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Bio       *string   `json:"bio"`
	CreatedAt time.Time `json:"created_at"`
	Slug      string    `json:"slug"`
}

type CatalogBook struct {
	ID             uuid.UUID          `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	PublisherID    pgtype.UUID        `json:"publisher_id"`
	CategoryID     pgtype.UUID        `json:"category_id"`
	Description    *string            `json:"description"`
	CoverUrl       *string            `json:"cover_url"`
	Language       string             `json:"language"`
	IsKidsFriendly bool               `json:"is_kids_friendly"`
	Status         string             `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Subtitle       *string            `json:"subtitle"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	ListenCount    int64              `json:"listen_count"`
	RatingAverage  pgtype.Numeric     `json:"rating_average"`
	RatingCount    int32              `json:"rating_count"`
	SearchDocument interface{}        `json:"search_document"`
}

type CatalogBookCategory struct {
	BookID     uuid.UUID `json:"book_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

type CatalogCategory struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	ParentID pgtype.UUID `json:"parent_id"`
}

type CatalogChapter struct {
	ID             uuid.UUID      `json:"id"`
	AudioEditionID uuid.UUID      `json:"audio_edition_id"`
	Title          string         `json:"title"`
	SortOrder      int32          `json:"sort_order"`
	StartSeconds   pgtype.Numeric `json:"start_seconds"`
	EndSeconds     pgtype.Numeric `json:"end_seconds"`
}

type CatalogCollection struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type CatalogCollectionBook struct {
	CollectionID uuid.UUID `json:"collection_id"`
	BookID       uuid.UUID `json:"book_id"`
	SortOrder    int32     `json:"sort_order"`
}

type CatalogPronunciationLexicon struct {
	ID        uuid.UUID   `json:"id"`
	BookID    pgtype.UUID `json:"book_id"`
	Grapheme  string      `json:"grapheme"`
	Phoneme   string      `json:"phoneme"`
	Language  string      `json:"language"`
	CreatedBy pgtype.UUID `json:"created_by"`
	CreatedAt time.Time   `json:"created_at"`
}

type CatalogPublisher struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	Slug      string    `json:"slug"`
}

type CatalogRightsGrant struct {
	ID                  uuid.UUID          `json:"id"`
	BookID              uuid.UUID          `json:"book_id"`
	PublisherID         pgtype.UUID        `json:"publisher_id"`
	Scope               string             `json:"scope"`
	RevenueSharePercent pgtype.Numeric     `json:"revenue_share_percent"`
	StartsAt            time.Time          `json:"starts_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	ContractRef         *string            `json:"contract_ref"`
	CreatedAt           time.Time          `json:"created_at"`
}

type CatalogTranscript struct {
	ID             uuid.UUID `json:"id"`
	AudioEditionID uuid.UUID `json:"audio_edition_id"`
	Language       string    `json:"language"`
	Content        []byte    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
}

type CatalogVoice struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Style     string    `json:"style"`
	IsDefault bool      `json:"is_default"`
	IsKids    bool      `json:"is_kids"`
	SortOrder int32     `json:"sort_order"`
	CreatedAt time.Time `json:"created_at"`
}

type CommerceCoupon struct {
	ID             uuid.UUID          `json:"id"`
	Code           string             `json:"code"`
	Kind           string             `json:"kind"`
	Value          int64              `json:"value"`
	MaxDiscountIrr *int64             `json:"max_discount_irr"`
	MinSubtotalIrr int64              `json:"min_subtotal_irr"`
	MaxRedemptions *int32             `json:"max_redemptions"`
	PerUserLimit   int32              `json:"per_user_limit"`
	StartsAt       time.Time          `json:"starts_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      time.Time          `json:"created_at"`
}

type CommerceCouponRedemption struct {
	ID          uuid.UUID `json:"id"`
	CouponID    uuid.UUID `json:"coupon_id"`
	UserID      uuid.UUID `json:"user_id"`
	OrderID     uuid.UUID `json:"order_id"`
	DiscountIrr int64     `json:"discount_irr"`
	CreatedAt   time.Time `json:"created_at"`
}

type CommerceEntitlement struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	BookID            pgtype.UUID        `json:"book_id"`
	AudioEditionID    pgtype.UUID        `json:"audio_edition_id"`
	Origin            string             `json:"origin"`
	SourceReferenceID pgtype.UUID        `json:"source_reference_id"`
	GrantedAt         time.Time          `json:"granted_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
}

type CommerceOrder struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Status         string             `json:"status"`
	SubtotalIrr    int64              `json:"subtotal_irr"`
	DiscountIrr    int64              `json:"discount_irr"`
	TotalIrr       int64              `json:"total_irr"`
	CouponID       pgtype.UUID        `json:"coupon_id"`
	IdempotencyKey *string            `json:"idempotency_key"`
	CreatedAt      time.Time          `json:"created_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

type CommerceOrderItem struct {
	ID              uuid.UUID   `json:"id"`
	OrderID         uuid.UUID   `json:"order_id"`
	AudioEditionID  uuid.UUID   `json:"audio_edition_id"`
	BookID          uuid.UUID   `json:"book_id"`
	UnitPriceIrr    int64       `json:"unit_price_irr"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	GiftMessage     *string     `json:"gift_message"`
}

type CommercePayment struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	Provider      string             `json:"provider"`
	AmountIrr     int64              `json:"amount_irr"`
	Status        string             `json:"status"`
	Authority     *string            `json:"authority"`
	ReferenceCode *string            `json:"reference_code"`
	FailureReason *string            `json:"failure_reason"`
	LedgerEntryID pgtype.UUID        `json:"ledger_entry_id"`
	CreatedAt     time.Time          `json:"created_at"`
	SettledAt     pgtype.Timestamptz `json:"settled_at"`
}

type CommerceRefund struct {
	ID          uuid.UUID          `json:"id"`
	OrderID     uuid.UUID          `json:"order_id"`
	UserID      uuid.UUID          `json:"user_id"`
	AmountIrr   int64              `json:"amount_irr"`
	Reason      *string            `json:"reason"`
	Status      string             `json:"status"`
	RequestedAt time.Time          `json:"requested_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy  pgtype.UUID        `json:"resolved_by"`
}

type CommerceSubscription struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	PlanID               uuid.UUID          `json:"plan_id"`
	Status               string             `json:"status"`
	AutoRenewFromWallet  bool               `json:"auto_renew_from_wallet"`
	StartedAt            time.Time          `json:"started_at"`
	ExpiresAt            time.Time          `json:"expires_at"`
	HoursConsumed        pgtype.Numeric     `json:"hours_consumed"`
	CanceledAt           pgtype.Timestamptz `json:"canceled_at"`
	CreatedAt            time.Time          `json:"created_at"`
	LastRenewalAttemptAt pgtype.Timestamptz `json:"last_renewal_attempt_at"`
	RenewalFailures      int32              `json:"renewal_failures"`
}

type CommerceSubscriptionPlan struct {
	ID             uuid.UUID `json:"id"`
	Code           string    `json:"code"`
	Name           string    `json:"name"`
	PriceIrr       int64     `json:"price_irr"`
	PeriodDays     int32     `json:"period_days"`
	MonthlyHourCap int32     `json:"monthly_hour_cap"`
	IsActive       bool      `json:"is_active"`
	SortOrder      int32     `json:"sort_order"`
}

type CommerceWalletLedger struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	EntryType     string      `json:"entry_type"`
	AmountIrr     int64       `json:"amount_irr"`
	Reason        string      `json:"reason"`
	ReferenceType *string     `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
	CreatedAt     time.Time   `json:"created_at"`
}

type DocumentArtifact struct {
	ID           uuid.UUID   `json:"id"`
	BookID       uuid.UUID   `json:"book_id"`
	DocumentID   uuid.UUID   `json:"document_id"`
	ArtifactType interface{} `json:"artifact_type"`
	Source       interface{} `json:"source"`
	StorageKey   string      `json:"storage_key"`
	Version      int32       `json:"version"`
	ContentHash  *string     `json:"content_hash"`
	Metadata     []byte      `json:"metadata"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

type HomeDemoContinueListening struct {
	ID              uuid.UUID `json:"id"`
	BookID          uuid.UUID `json:"book_id"`
	ProgressPercent int32     `json:"progress_percent"`
}

type HomeDemoRecommendation struct {
	ID        uuid.UUID `json:"id"`
	BookID    uuid.UUID `json:"book_id"`
	Tag       string    `json:"tag"`
	Type      string    `json:"type"`
	SortOrder int32     `json:"sort_order"`
}

type HomeDemoSample struct {
	ID     uuid.UUID `json:"id"`
	BookID uuid.UUID `json:"book_id"`
	AiTag  string    `json:"ai_tag"`
}

type HomeLead struct {
	ID           uuid.UUID `json:"id"`
	FullName     string    `json:"full_name"`
	PhoneNumber  *string   `json:"phone_number"`
	Email        *string   `json:"email"`
	UserType     string    `json:"user_type"`
	InterestTags []string  `json:"interest_tags"`
	Consent      bool      `json:"consent"`
	Source       *string   `json:"source"`
	LandingPath  *string   `json:"landing_path"`
	Referrer     *string   `json:"referrer"`
	UtmSource    *string   `json:"utm_source"`
	UtmMedium    *string   `json:"utm_medium"`
	UtmCampaign  *string   `json:"utm_campaign"`
	CreatedAt    time.Time `json:"created_at"`
}

type HomeLocalizationContent struct {
	ID       bool   `json:"id"`
	Title    string `json:"title"`
	Subtitle string `json:"subtitle"`
}

type HomeLocalizationLanguage struct {
	Code      string `json:"code"`
	Label     string `json:"label"`
	SortOrder int32  `json:"sort_order"`
}

type HomeLocalizationSample struct {
	ID           uuid.UUID `json:"id"`
	Title        string    `json:"title"`
	CoverUrl     *string   `json:"cover_url"`
	LanguageCode string    `json:"language_code"`
	SortOrder    int32     `json:"sort_order"`
}

type HomeLocalizationTopic struct {
	ID        uuid.UUID `json:"id"`
	Topic     string    `json:"topic"`
	SortOrder int32     `json:"sort_order"`
}

type HomeSocialProofPartner struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	LogoUrl   *string   `json:"logo_url"`
	SortOrder int32     `json:"sort_order"`
}

type HomeSocialProofStat struct {
	ID        uuid.UUID `json:"id"`
	Label     string    `json:"label"`
	Value     string    `json:"value"`
	SortOrder int32     `json:"sort_order"`
}

type HomeSocialProofTestimonial struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Role      string    `json:"role"`
	Message   string    `json:"message"`
	AvatarUrl *string   `json:"avatar_url"`
	SortOrder int32     `json:"sort_order"`
}

type HomeStat struct {
	Key          string `json:"key"`
	Label        string `json:"label"`
	Value        int64  `json:"value"`
	DisplayValue string `json:"display_value"`
	SortOrder    int32  `json:"sort_order"`
}

type IdentityDevice struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	Platform          string             `json:"platform"`
	PushToken         *string            `json:"push_token"`
	AppVersion        *string            `json:"app_version"`
	LastActiveAt      time.Time          `json:"last_active_at"`
	CreatedAt         time.Time          `json:"created_at"`
	DeviceFingerprint *string            `json:"device_fingerprint"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	Name              *string            `json:"name"`
}

type IdentityOtpCode struct {
	ID           uuid.UUID          `json:"id"`
	PhoneNumber  string             `json:"phone_number"`
	CodeHash     string             `json:"code_hash"`
	Purpose      string             `json:"purpose"`
	AttemptCount int32              `json:"attempt_count"`
	MaxAttempts  int32              `json:"max_attempts"`
	ExpiresAt    time.Time          `json:"expires_at"`
	ConsumedAt   pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt    time.Time          `json:"created_at"`
}

type IdentityRefreshToken struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	DeviceID     pgtype.UUID        `json:"device_id"`
	TokenHash    string             `json:"token_hash"`
	ExpiresAt    time.Time          `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt    time.Time          `json:"created_at"`
	FamilyID     uuid.UUID          `json:"family_id"`
	ReplacedByID pgtype.UUID        `json:"replaced_by_id"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
}

type IdentityUser struct {
	ID              uuid.UUID          `json:"id"`
	PhoneNumber     string             `json:"phone_number"`
	FullName        *string            `json:"full_name"`
	Email           *string            `json:"email"`
	Role            string             `json:"role"`
	Status          string             `json:"status"`
	KidsModeEnabled bool               `json:"kids_mode_enabled"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	SuspendedReason *string            `json:"suspended_reason"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
}

type IdentityUserRole struct {
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	GrantedAt time.Time `json:"granted_at"`
}

type IngestSubmission struct {
	ID               uuid.UUID          `json:"id"`
	AiBookID         uuid.UUID          `json:"ai_book_id"`
	AiDocumentID     uuid.UUID          `json:"ai_document_id"`
	CatalogBookID    pgtype.UUID        `json:"catalog_book_id"`
	Title            string             `json:"title"`
	Author           *string            `json:"author"`
	Description      *string            `json:"description"`
	PdfFileName      string             `json:"pdf_file_name"`
	PdfStorageKey    string             `json:"pdf_storage_key"`
	PdfSizeBytes     int64              `json:"pdf_size_bytes"`
	CoverStorageKey  *string            `json:"cover_storage_key"`
	WantTts          bool               `json:"want_tts"`
	WantAssistant    bool               `json:"want_assistant"`
	DispatchStatus   string             `json:"dispatch_status"`
	DispatchError    *string            `json:"dispatch_error"`
	DispatchedAt     pgtype.Timestamptz `json:"dispatched_at"`
	CreatedBy        *string            `json:"created_by"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	CatalogEditionID pgtype.UUID        `json:"catalog_edition_id"`
	AudioStatus      string             `json:"audio_status"`
	AudioError       *string            `json:"audio_error"`
	AudioSyncedAt    pgtype.Timestamptz `json:"audio_synced_at"`
	AudioSignature   *string            `json:"audio_signature"`
}

type Job struct {
	ID           uuid.UUID          `json:"id"`
	BookID       uuid.UUID          `json:"book_id"`
	Status       interface{}        `json:"status"`
	CurrentStep  *string            `json:"current_step"`
	Progress     int32              `json:"progress"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	FailedAt     pgtype.Timestamptz `json:"failed_at"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type JobStep struct {
	ID           uuid.UUID          `json:"id"`
	JobID        uuid.UUID          `json:"job_id"`
	Step         string             `json:"step"`
	Status       interface{}        `json:"status"`
	Progress     int32              `json:"progress"`
	Attempt      int32              `json:"attempt"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

type JobsOutbox struct {
	ID           uuid.UUID          `json:"id"`
	TaskType     string             `json:"task_type"`
	Payload      []byte             `json:"payload"`
	Queue        string             `json:"queue"`
	MaxRetry     int32              `json:"max_retry"`
	AvailableAt  time.Time          `json:"available_at"`
	DedupeKey    *string            `json:"dedupe_key"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	LastError    *string            `json:"last_error"`
	CreatedAt    time.Time          `json:"created_at"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
}

type KidsAllowedPrompt struct {
	ID         uuid.UUID `json:"id"`
	Label      string    `json:"label"`
	PromptText string    `json:"prompt_text"`
	MinAge     int32     `json:"min_age"`
	MaxAge     int32     `json:"max_age"`
	SortOrder  int32     `json:"sort_order"`
	IsActive   bool      `json:"is_active"`
}

type KidsChildProfile struct {
	ID           uuid.UUID `json:"id"`
	ParentUserID uuid.UUID `json:"parent_user_id"`
	DisplayName  string    `json:"display_name"`
	BirthYear    *int32    `json:"birth_year"`
	AgeYears     int32     `json:"age_years"`
	AvatarKey    *string   `json:"avatar_key"`
	IsActive     bool      `json:"is_active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type KidsContentApproval struct {
	ID             uuid.UUID `json:"id"`
	ChildProfileID uuid.UUID `json:"child_profile_id"`
	BookID         uuid.UUID `json:"book_id"`
	Decision       string    `json:"decision"`
	DecidedBy      uuid.UUID `json:"decided_by"`
	DecidedAt      time.Time `json:"decided_at"`
}

type KidsParentalControl struct {
	ChildProfileID       uuid.UUID `json:"child_profile_id"`
	DailyLimitMinutes    int32     `json:"daily_limit_minutes"`
	AllowedFromMinute    int32     `json:"allowed_from_minute"`
	AllowedToMinute      int32     `json:"allowed_to_minute"`
	MaxContentAge        int32     `json:"max_content_age"`
	ApprovalMode         string    `json:"approval_mode"`
	ExitPinHash          *string   `json:"exit_pin_hash"`
	AutodownloadWifiOnly bool      `json:"autodownload_wifi_only"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type KnowledgeVersion struct {
	ID          uuid.UUID          `json:"id"`
	BookID      uuid.UUID          `json:"book_id"`
	Version     int32              `json:"version"`
	Status      interface{}        `json:"status"`
	ActivatedAt pgtype.Timestamptz `json:"activated_at"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
}

type LibraryBookmark struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	AudioEditionID  uuid.UUID      `json:"audio_edition_id"`
	BookID          uuid.UUID      `json:"book_id"`
	PositionSeconds pgtype.Numeric `json:"position_seconds"`
	Label           *string        `json:"label"`
	Summary         *string        `json:"summary"`
	SummaryStatus   string         `json:"summary_status"`
	CreatedAt       time.Time      `json:"created_at"`
}

type LibraryClip struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	AudioEditionID uuid.UUID      `json:"audio_edition_id"`
	StartSeconds   pgtype.Numeric `json:"start_seconds"`
	EndSeconds     pgtype.Numeric `json:"end_seconds"`
	Status         string         `json:"status"`
	StorageKey     *string        `json:"storage_key"`
	CreatedAt      time.Time      `json:"created_at"`
}

type LibraryHighlight struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	AudioEditionID uuid.UUID      `json:"audio_edition_id"`
	BookID         uuid.UUID      `json:"book_id"`
	StartSeconds   pgtype.Numeric `json:"start_seconds"`
	EndSeconds     pgtype.Numeric `json:"end_seconds"`
	Quote          string         `json:"quote"`
	CreatedAt      time.Time      `json:"created_at"`
}

type LibraryListeningEvent struct {
	ID              uuid.UUID   `json:"id"`
	UserID          uuid.UUID   `json:"user_id"`
	ProfileID       pgtype.UUID `json:"profile_id"`
	AudioEditionID  uuid.UUID   `json:"audio_edition_id"`
	BookID          uuid.UUID   `json:"book_id"`
	SecondsListened int32       `json:"seconds_listened"`
	OccurredAt      time.Time   `json:"occurred_at"`
	CreatedAt       time.Time   `json:"created_at"`
}

type LibraryListeningPosition struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	ProfileID       pgtype.UUID    `json:"profile_id"`
	AudioEditionID  uuid.UUID      `json:"audio_edition_id"`
	BookID          uuid.UUID      `json:"book_id"`
	PositionSeconds pgtype.Numeric `json:"position_seconds"`
	DurationSeconds pgtype.Numeric `json:"duration_seconds"`
	IsFinished      bool           `json:"is_finished"`
	DeviceUpdatedAt time.Time      `json:"device_updated_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type LibraryNote struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	AudioEditionID  uuid.UUID      `json:"audio_edition_id"`
	BookID          uuid.UUID      `json:"book_id"`
	PositionSeconds pgtype.Numeric `json:"position_seconds"`
	Body            string         `json:"body"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type LibraryShelfItem struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	BookID    uuid.UUID `json:"book_id"`
	Shelf     string    `json:"shelf"`
	CreatedAt time.Time `json:"created_at"`
}

type MediaAudioAsset struct {
	ID              uuid.UUID `json:"id"`
	AudioEditionID  uuid.UUID `json:"audio_edition_id"`
	StorageKey      string    `json:"storage_key"`
	Format          string    `json:"format"`
	BitrateKbps     int32     `json:"bitrate_kbps"`
	DurationSeconds int32     `json:"duration_seconds"`
	Checksum        *string   `json:"checksum"`
	CreatedAt       time.Time `json:"created_at"`
}

type MediaTranscodeJob struct {
	ID             uuid.UUID `json:"id"`
	AudioEditionID uuid.UUID `json:"audio_edition_id"`
	Status         string    `json:"status"`
	InputKey       *string   `json:"input_key"`
	OutputFormat   *string   `json:"output_format"`
	Error          *string   `json:"error"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
