// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCouponRedemptions = `-- name: CountCouponRedemptions :one
SELECT count(*) FROM commerce.coupon_redemptions WHERE coupon_id = $1
`

func (q *Queries) CountCouponRedemptions(ctx context.Context, couponID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCouponRedemptions, couponID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCouponRedemptionsForUser = `-- name: CountCouponRedemptionsForUser :one
SELECT count(*) FROM commerce.coupon_redemptions WHERE coupon_id = $1 AND user_id = $2
`

type CountCouponRedemptionsForUserParams struct {
	CouponID uuid.UUID `json:"coupon_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) CountCouponRedemptionsForUser(ctx context.Context, arg CountCouponRedemptionsForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCouponRedemptionsForUser, arg.CouponID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCouponRedemption = `-- name: CreateCouponRedemption :exec
INSERT INTO commerce.coupon_redemptions (coupon_id, user_id, order_id, discount_irr)
VALUES ($1, $2, $3, $4)
`

type CreateCouponRedemptionParams struct {
	CouponID    uuid.UUID `json:"coupon_id"`
	UserID      uuid.UUID `json:"user_id"`
	OrderID     uuid.UUID `json:"order_id"`
	DiscountIrr int64     `json:"discount_irr"`
}

func (q *Queries) CreateCouponRedemption(ctx context.Context, arg CreateCouponRedemptionParams) error {
	_, err := q.db.Exec(ctx, createCouponRedemption,
		arg.CouponID,
		arg.UserID,
		arg.OrderID,
		arg.DiscountIrr,
	)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO commerce.orders (user_id, status, subtotal_irr, discount_irr, total_irr, coupon_id, idempotency_key)
VALUES ($1, 'pending', $2, $3, $4, $5, $6)
RETURNING id, user_id, status, subtotal_irr, discount_irr, total_irr, coupon_id, idempotency_key, created_at, paid_at, updated_at
`

type CreateOrderParams struct {
	UserID         uuid.UUID   `json:"user_id"`
	SubtotalIrr    int64       `json:"subtotal_irr"`
	DiscountIrr    int64       `json:"discount_irr"`
	TotalIrr       int64       `json:"total_irr"`
	CouponID       pgtype.UUID `json:"coupon_id"`
	IdempotencyKey *string     `json:"idempotency_key"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CommerceOrder, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.UserID,
		arg.SubtotalIrr,
		arg.DiscountIrr,
		arg.TotalIrr,
		arg.CouponID,
		arg.IdempotencyKey,
	)
	var i CommerceOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalIrr,
		&i.DiscountIrr,
		&i.TotalIrr,
		&i.CouponID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO commerce.order_items (order_id, audio_edition_id, book_id, unit_price_irr, recipient_user_id, gift_message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, order_id, audio_edition_id, book_id, unit_price_irr, recipient_user_id, gift_message
`

type CreateOrderItemParams struct {
	OrderID         uuid.UUID   `json:"order_id"`
	AudioEditionID  uuid.UUID   `json:"audio_edition_id"`
	BookID          uuid.UUID   `json:"book_id"`
	UnitPriceIrr    int64       `json:"unit_price_irr"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	GiftMessage     *string     `json:"gift_message"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (CommerceOrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.AudioEditionID,
		arg.BookID,
		arg.UnitPriceIrr,
		arg.RecipientUserID,
		arg.GiftMessage,
	)
	var i CommerceOrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.AudioEditionID,
		&i.BookID,
		&i.UnitPriceIrr,
		&i.RecipientUserID,
		&i.GiftMessage,
	)
	return i, err
}

const createRefund = `-- name: CreateRefund :one
INSERT INTO commerce.refunds (order_id, user_id, amount_irr, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, user_id, amount_irr, reason, status, requested_at, resolved_at, resolved_by
`

type CreateRefundParams struct {
	OrderID   uuid.UUID `json:"order_id"`
	UserID    uuid.UUID `json:"user_id"`
	AmountIrr int64     `json:"amount_irr"`
	Reason    *string   `json:"reason"`
}

func (q *Queries) CreateRefund(ctx context.Context, arg CreateRefundParams) (CommerceRefund, error) {
	row := q.db.QueryRow(ctx, createRefund,
		arg.OrderID,
		arg.UserID,
		arg.AmountIrr,
		arg.Reason,
	)
	var i CommerceRefund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AmountIrr,
		&i.Reason,
		&i.Status,
		&i.RequestedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, kind, value, max_discount_irr, min_subtotal_irr, max_redemptions, per_user_limit, starts_at, expires_at, is_active, created_at FROM commerce.coupons WHERE code = $1
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (CommerceCoupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, code)
	var i CommerceCoupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.MaxDiscountIrr,
		&i.MinSubtotalIrr,
		&i.MaxRedemptions,
		&i.PerUserLimit,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, status, subtotal_irr, discount_irr, total_irr, coupon_id, idempotency_key, created_at, paid_at, updated_at FROM commerce.orders WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (CommerceOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i CommerceOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalIrr,
		&i.DiscountIrr,
		&i.TotalIrr,
		&i.CouponID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, user_id, status, subtotal_irr, discount_irr, total_irr, coupon_id, idempotency_key, created_at, paid_at, updated_at FROM commerce.orders
WHERE user_id = $1 AND idempotency_key = $2
`

type GetOrderByIdempotencyKeyParams struct {
	UserID         uuid.UUID `json:"user_id"`
	IdempotencyKey *string   `json:"idempotency_key"`
}

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, arg GetOrderByIdempotencyKeyParams) (CommerceOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i CommerceOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalIrr,
		&i.DiscountIrr,
		&i.TotalIrr,
		&i.CouponID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefundByID = `-- name: GetRefundByID :one
SELECT id, order_id, user_id, amount_irr, reason, status, requested_at, resolved_at, resolved_by FROM commerce.refunds WHERE id = $1
`

func (q *Queries) GetRefundByID(ctx context.Context, id uuid.UUID) (CommerceRefund, error) {
	row := q.db.QueryRow(ctx, getRefundByID, id)
	var i CommerceRefund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AmountIrr,
		&i.Reason,
		&i.Status,
		&i.RequestedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}

const getUsableCouponByCode = `-- name: GetUsableCouponByCode :one
SELECT id, code, kind, value, max_discount_irr, min_subtotal_irr, max_redemptions, per_user_limit, starts_at, expires_at, is_active, created_at FROM commerce.coupons
WHERE code = $1
  AND is_active
  AND starts_at <= now()
  AND (expires_at IS NULL OR expires_at > now())
`

// GetUsableCouponByCode evaluates the validity *window* in the database.
//
// The window has to be judged by one clock. Comparing a Postgres-issued
// starts_at against the API host's time.Now() rejects a perfectly valid
// coupon whenever the two machines differ by a few seconds — which they
// will, since they are different machines. The amount rules (subtotal
// floor, caps, redemption limits) stay in Go where they are testable;
// only the time comparison moves here.
func (q *Queries) GetUsableCouponByCode(ctx context.Context, code string) (CommerceCoupon, error) {
	row := q.db.QueryRow(ctx, getUsableCouponByCode, code)
	var i CommerceCoupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Kind,
		&i.Value,
		&i.MaxDiscountIrr,
		&i.MinSubtotalIrr,
		&i.MaxRedemptions,
		&i.PerUserLimit,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, audio_edition_id, book_id, unit_price_irr, recipient_user_id, gift_message FROM commerce.order_items WHERE order_id = $1
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]CommerceOrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceOrderItem
	for rows.Next() {
		var i CommerceOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.AudioEditionID,
			&i.BookID,
			&i.UnitPriceIrr,
			&i.RecipientUserID,
			&i.GiftMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersForUser = `-- name: ListOrdersForUser :many
SELECT id, user_id, status, subtotal_irr, discount_irr, total_irr, coupon_id, idempotency_key, created_at, paid_at, updated_at, count(*) OVER () AS total_count FROM commerce.orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListOrdersForUserRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Status         string             `json:"status"`
	SubtotalIrr    int64              `json:"subtotal_irr"`
	DiscountIrr    int64              `json:"discount_irr"`
	TotalIrr       int64              `json:"total_irr"`
	CouponID       pgtype.UUID        `json:"coupon_id"`
	IdempotencyKey *string            `json:"idempotency_key"`
	CreatedAt      time.Time          `json:"created_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	TotalCount     int64              `json:"total_count"`
}

func (q *Queries) ListOrdersForUser(ctx context.Context, arg ListOrdersForUserParams) ([]ListOrdersForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrdersForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrdersForUserRow
	for rows.Next() {
		var i ListOrdersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.SubtotalIrr,
			&i.DiscountIrr,
			&i.TotalIrr,
			&i.CouponID,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.PaidAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundsForOrder = `-- name: ListRefundsForOrder :many
SELECT id, order_id, user_id, amount_irr, reason, status, requested_at, resolved_at, resolved_by FROM commerce.refunds WHERE order_id = $1 ORDER BY requested_at DESC
`

func (q *Queries) ListRefundsForOrder(ctx context.Context, orderID uuid.UUID) ([]CommerceRefund, error) {
	rows, err := q.db.Query(ctx, listRefundsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceRefund
	for rows.Next() {
		var i CommerceRefund
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.AmountIrr,
			&i.Reason,
			&i.Status,
			&i.RequestedAt,
			&i.ResolvedAt,
			&i.ResolvedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderFailed = `-- name: MarkOrderFailed :exec
UPDATE commerce.orders
SET status = 'failed', updated_at = now()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkOrderFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOrderFailed, id)
	return err
}

const markOrderPaid = `-- name: MarkOrderPaid :one
UPDATE commerce.orders
SET status = 'paid', paid_at = now(), updated_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, status, subtotal_irr, discount_irr, total_irr, coupon_id, idempotency_key, created_at, paid_at, updated_at
`

func (q *Queries) MarkOrderPaid(ctx context.Context, id uuid.UUID) (CommerceOrder, error) {
	row := q.db.QueryRow(ctx, markOrderPaid, id)
	var i CommerceOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.SubtotalIrr,
		&i.DiscountIrr,
		&i.TotalIrr,
		&i.CouponID,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.PaidAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderRefunded = `-- name: MarkOrderRefunded :exec
UPDATE commerce.orders
SET status = 'refunded', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkOrderRefunded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOrderRefunded, id)
	return err
}

const resolveRefund = `-- name: ResolveRefund :one
UPDATE commerce.refunds
SET status = $2, resolved_at = now(), resolved_by = $3
WHERE id = $1 AND status = 'requested'
RETURNING id, order_id, user_id, amount_irr, reason, status, requested_at, resolved_at, resolved_by
`

type ResolveRefundParams struct {
	ID         uuid.UUID   `json:"id"`
	Status     string      `json:"status"`
	ResolvedBy pgtype.UUID `json:"resolved_by"`
}

func (q *Queries) ResolveRefund(ctx context.Context, arg ResolveRefundParams) (CommerceRefund, error) {
	row := q.db.QueryRow(ctx, resolveRefund, arg.ID, arg.Status, arg.ResolvedBy)
	var i CommerceRefund
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AmountIrr,
		&i.Reason,
		&i.Status,
		&i.RequestedAt,
		&i.ResolvedAt,
		&i.ResolvedBy,
	)
	return i, err
}
