// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// سقف ساعتی: Spotify پانزده ساعت در ماه می‌دهد و استوری‌تل پلن‌های
	// ۱۵/۳۰/۴۵ ساعته. «نامحدود» فقط پرمصرف‌ترین کاربران را جذب می‌کند و
	// حاشیه سود را می‌بلعد (02-business.md) — پس مصرف شمرده می‌شود.
	AddSubscriptionHours(ctx context.Context, arg AddSubscriptionHoursParams) (CommerceSubscription, error)
	CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (CommerceSubscription, error)
	CountCouponRedemptions(ctx context.Context, couponID uuid.UUID) (int64, error)
	CountCouponRedemptionsForUser(ctx context.Context, arg CountCouponRedemptionsForUserParams) (int64, error)
	CreateCouponRedemption(ctx context.Context, arg CreateCouponRedemptionParams) error
	CreateEntitlement(ctx context.Context, arg CreateEntitlementParams) (CommerceEntitlement, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CommerceOrder, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (CommerceOrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CommercePayment, error)
	CreateRefund(ctx context.Context, arg CreateRefundParams) (CommerceRefund, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CommerceSubscription, error)
	CreateWalletLedgerEntry(ctx context.Context, arg CreateWalletLedgerEntryParams) (CommerceWalletLedger, error)
	// ExpireDueSubscriptions عمداً بعد از تمدید اجرا می‌شود و در همان
	// handler، تا مسابقه‌ای که قبلاً بین این دو job وجود داشت ممکن نباشد.
	ExpireDueSubscriptions(ctx context.Context) ([]CommerceSubscription, error)
	ExtendSubscription(ctx context.Context, arg ExtendSubscriptionParams) (CommerceSubscription, error)
	GetActiveSubscriptionForUser(ctx context.Context, userID uuid.UUID) (CommerceSubscription, error)
	GetCouponByCode(ctx context.Context, code string) (CommerceCoupon, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (CommerceOrder, error)
	GetOrderByIdempotencyKey(ctx context.Context, arg GetOrderByIdempotencyKeyParams) (CommerceOrder, error)
	GetPaymentByAuthority(ctx context.Context, arg GetPaymentByAuthorityParams) (CommercePayment, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (CommercePayment, error)
	GetRefundByID(ctx context.Context, id uuid.UUID) (CommerceRefund, error)
	GetSubscriptionByID(ctx context.Context, id uuid.UUID) (CommerceSubscription, error)
	GetSubscriptionPlanByCode(ctx context.Context, code string) (CommerceSubscriptionPlan, error)
	GetSubscriptionPlanByID(ctx context.Context, id uuid.UUID) (CommerceSubscriptionPlan, error)
	// GetUsableCouponByCode evaluates the validity *window* in the database.
	//
	// The window has to be judged by one clock. Comparing a Postgres-issued
	// starts_at against the API host's time.Now() rejects a perfectly valid
	// coupon whenever the two machines differ by a few seconds — which they
	// will, since they are different machines. The amount rules (subtotal
	// floor, caps, redemption limits) stay in Go where they are testable;
	// only the time comparison moves here.
	GetUsableCouponByCode(ctx context.Context, code string) (CommerceCoupon, error)
	GetWalletBalance(ctx context.Context, userID uuid.UUID) (int64, error)
	// خرید دو بار همان نسخه نباید دو ردیف بسازد. ON CONFLICT روی همان
	// ایندکس جزئی یکتای مهاجرت 00008 می‌نشیند، پس دو کلیک هم‌زمان «خرید»
	// به یک entitlement می‌رسند نه دو تا.
	GrantEntitlementIdempotent(ctx context.Context, arg GrantEntitlementIdempotentParams) (CommerceEntitlement, error)
	IsUserEntitledToBook(ctx context.Context, arg IsUserEntitledToBookParams) (bool, error)
	// دسترسی در سطح AudioEdition سنجیده می‌شود نه فقط Book: خرید نسخه
	// «آرام» حق پخش نسخه «نمایشی» را نمی‌دهد چون قیمتشان مستقل است. اما
	// entitlement با audio_edition_id تهی (اشتراک، دسترسی سازمانی) کل کتاب
	// را پوشش می‌دهد.
	IsUserEntitledToEdition(ctx context.Context, arg IsUserEntitledToEditionParams) (bool, error)
	ListActiveEntitlementsForUser(ctx context.Context, userID uuid.UUID) ([]CommerceEntitlement, error)
	ListActiveSubscriptionPlans(ctx context.Context) ([]CommerceSubscriptionPlan, error)
	ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]CommerceOrderItem, error)
	ListOrdersForUser(ctx context.Context, arg ListOrdersForUserParams) ([]ListOrdersForUserRow, error)
	ListRefundsForOrder(ctx context.Context, orderID uuid.UUID) ([]CommerceRefund, error)
	// ListSubscriptionsDueForRenewal عمداً ردیف‌های **گذشته از سررسید** را هم
	// برمی‌گرداند، نه فقط آن‌هایی که تا یک ساعت آینده سررسید می‌شوند.
	//
	// باگی که این حل می‌کند: نسخه قبلی فقط `status = 'active'` را می‌دید و
	// expire هم ساعتی اجرا می‌شد. اگر worker چند ساعت پایین بود — یا صرفاً
	// expire زودتر از renew اجرا می‌شد — اشتراک به 'expired' می‌رفت و
	// sweep تمدید دیگر هرگز نمی‌دیدش. کاربری که تمدید خودکار خواسته بود
	// بی‌صدا دسترسی‌اش را از دست می‌داد و هیچ‌کس خبردار نمی‌شد.
	//
	// حالا پنجره جبران (grace) هم اشتراک‌های تازه‌منقضی را برمی‌گرداند، و
	// last_renewal_attempt_at جلوی ناخنک زدن ساعتی به کیف پول خالی را
	// می‌گیرد.
	ListSubscriptionsDueForRenewal(ctx context.Context, arg ListSubscriptionsDueForRenewalParams) ([]CommerceSubscription, error)
	ListWalletLedgerForUser(ctx context.Context, arg ListWalletLedgerForUserParams) ([]ListWalletLedgerForUserRow, error)
	LockPaymentForSettlement(ctx context.Context, id uuid.UUID) (CommercePayment, error)
	// LockWallet قفل مشورتی سطح تراکنش روی کیف پول یک کاربر می‌گیرد.
	//
	// بدون این، برداشت اتمیک نیست: دو درخواست هم‌زمان هر دو موجودی را کافی
	// می‌بینند و هر دو ردیف debit می‌سازند — کیف پول منفی می‌شود و چون دفتر
	// کل فقط‌افزودنی است، اصلاحش یعنی ثبت یک credit جبرانی و توضیح دادن به
	// کاربر. یک ستون balance با CHECK این را حل نمی‌کرد چون تصمیم صریح
	// 08-decisions.md نداشتن ستون balance است؛ قفل، همان تضمین را بدون
	// شکستن آن تصمیم می‌دهد.
	//
	// hashtextextended به جای hashtext چون خروجی bigint می‌دهد و
	// pg_advisory_xact_lock نسخه تک‌آرگومانی bigint دارد.
	LockWallet(ctx context.Context, dollar_1 string) error
	MarkOrderFailed(ctx context.Context, id uuid.UUID) error
	MarkOrderPaid(ctx context.Context, id uuid.UUID) (CommerceOrder, error)
	MarkOrderRefunded(ctx context.Context, id uuid.UUID) error
	MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (CommercePayment, error)
	MarkPaymentSucceeded(ctx context.Context, arg MarkPaymentSucceededParams) (CommercePayment, error)
	MarkRenewalAttempt(ctx context.Context, arg MarkRenewalAttemptParams) error
	// تمدید موفق باید اشتراکِ تازه‌منقضی را دوباره فعال کند، وگرنه کاربر
	// پول داده و همچنان دسترسی ندارد.
	ReactivateSubscription(ctx context.Context, id uuid.UUID) error
	ResolveRefund(ctx context.Context, arg ResolveRefundParams) (CommerceRefund, error)
	RevokeEntitlement(ctx context.Context, id uuid.UUID) error
	RevokeEntitlementsForOrder(ctx context.Context, sourceReferenceID pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
