// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addSubscriptionHours = `-- name: AddSubscriptionHours :one
UPDATE commerce.subscriptions
SET hours_consumed = hours_consumed + $2
WHERE id = $1
RETURNING id, user_id, plan_id, status, auto_renew_from_wallet, started_at, expires_at, hours_consumed, canceled_at, created_at, last_renewal_attempt_at, renewal_failures
`

type AddSubscriptionHoursParams struct {
	ID            uuid.UUID      `json:"id"`
	HoursConsumed pgtype.Numeric `json:"hours_consumed"`
}

// سقف ساعتی: Spotify پانزده ساعت در ماه می‌دهد و استوری‌تل پلن‌های
// ۱۵/۳۰/۴۵ ساعته. «نامحدود» فقط پرمصرف‌ترین کاربران را جذب می‌کند و
// حاشیه سود را می‌بلعد (02-business.md) — پس مصرف شمرده می‌شود.
func (q *Queries) AddSubscriptionHours(ctx context.Context, arg AddSubscriptionHoursParams) (CommerceSubscription, error) {
	row := q.db.QueryRow(ctx, addSubscriptionHours, arg.ID, arg.HoursConsumed)
	var i CommerceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.AutoRenewFromWallet,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.HoursConsumed,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.LastRenewalAttemptAt,
		&i.RenewalFailures,
	)
	return i, err
}

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE commerce.subscriptions
SET status = 'canceled', canceled_at = now(), auto_renew_from_wallet = false
WHERE id = $1 AND user_id = $2 AND status = 'active'
RETURNING id, user_id, plan_id, status, auto_renew_from_wallet, started_at, expires_at, hours_consumed, canceled_at, created_at, last_renewal_attempt_at, renewal_failures
`

type CancelSubscriptionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (CommerceSubscription, error) {
	row := q.db.QueryRow(ctx, cancelSubscription, arg.ID, arg.UserID)
	var i CommerceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.AutoRenewFromWallet,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.HoursConsumed,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.LastRenewalAttemptAt,
		&i.RenewalFailures,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO commerce.subscriptions (user_id, plan_id, expires_at, auto_renew_from_wallet)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, plan_id, status, auto_renew_from_wallet, started_at, expires_at, hours_consumed, canceled_at, created_at, last_renewal_attempt_at, renewal_failures
`

type CreateSubscriptionParams struct {
	UserID              uuid.UUID `json:"user_id"`
	PlanID              uuid.UUID `json:"plan_id"`
	ExpiresAt           time.Time `json:"expires_at"`
	AutoRenewFromWallet bool      `json:"auto_renew_from_wallet"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (CommerceSubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.PlanID,
		arg.ExpiresAt,
		arg.AutoRenewFromWallet,
	)
	var i CommerceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.AutoRenewFromWallet,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.HoursConsumed,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.LastRenewalAttemptAt,
		&i.RenewalFailures,
	)
	return i, err
}

const expireDueSubscriptions = `-- name: ExpireDueSubscriptions :many
UPDATE commerce.subscriptions
SET status = 'expired'
WHERE status = 'active' AND expires_at <= now()
RETURNING id, user_id, plan_id, status, auto_renew_from_wallet, started_at, expires_at, hours_consumed, canceled_at, created_at, last_renewal_attempt_at, renewal_failures
`

// ExpireDueSubscriptions عمداً بعد از تمدید اجرا می‌شود و در همان
// handler، تا مسابقه‌ای که قبلاً بین این دو job وجود داشت ممکن نباشد.
func (q *Queries) ExpireDueSubscriptions(ctx context.Context) ([]CommerceSubscription, error) {
	rows, err := q.db.Query(ctx, expireDueSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceSubscription
	for rows.Next() {
		var i CommerceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.AutoRenewFromWallet,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.HoursConsumed,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.LastRenewalAttemptAt,
			&i.RenewalFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const extendSubscription = `-- name: ExtendSubscription :one
UPDATE commerce.subscriptions
SET expires_at = expires_at + make_interval(days => $2::int), hours_consumed = 0
WHERE id = $1
RETURNING id, user_id, plan_id, status, auto_renew_from_wallet, started_at, expires_at, hours_consumed, canceled_at, created_at, last_renewal_attempt_at, renewal_failures
`

type ExtendSubscriptionParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 int32     `json:"column_2"`
}

func (q *Queries) ExtendSubscription(ctx context.Context, arg ExtendSubscriptionParams) (CommerceSubscription, error) {
	row := q.db.QueryRow(ctx, extendSubscription, arg.ID, arg.Column2)
	var i CommerceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.AutoRenewFromWallet,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.HoursConsumed,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.LastRenewalAttemptAt,
		&i.RenewalFailures,
	)
	return i, err
}

const getActiveSubscriptionForUser = `-- name: GetActiveSubscriptionForUser :one
SELECT id, user_id, plan_id, status, auto_renew_from_wallet, started_at, expires_at, hours_consumed, canceled_at, created_at, last_renewal_attempt_at, renewal_failures FROM commerce.subscriptions
WHERE user_id = $1 AND status = 'active' AND expires_at > now()
ORDER BY expires_at DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscriptionForUser(ctx context.Context, userID uuid.UUID) (CommerceSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscriptionForUser, userID)
	var i CommerceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.AutoRenewFromWallet,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.HoursConsumed,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.LastRenewalAttemptAt,
		&i.RenewalFailures,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, plan_id, status, auto_renew_from_wallet, started_at, expires_at, hours_consumed, canceled_at, created_at, last_renewal_attempt_at, renewal_failures FROM commerce.subscriptions WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (CommerceSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i CommerceSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.AutoRenewFromWallet,
		&i.StartedAt,
		&i.ExpiresAt,
		&i.HoursConsumed,
		&i.CanceledAt,
		&i.CreatedAt,
		&i.LastRenewalAttemptAt,
		&i.RenewalFailures,
	)
	return i, err
}

const getSubscriptionPlanByCode = `-- name: GetSubscriptionPlanByCode :one
SELECT id, code, name, price_irr, period_days, monthly_hour_cap, is_active, sort_order FROM commerce.subscription_plans WHERE code = $1 AND is_active
`

func (q *Queries) GetSubscriptionPlanByCode(ctx context.Context, code string) (CommerceSubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanByCode, code)
	var i CommerceSubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PriceIrr,
		&i.PeriodDays,
		&i.MonthlyHourCap,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const getSubscriptionPlanByID = `-- name: GetSubscriptionPlanByID :one
SELECT id, code, name, price_irr, period_days, monthly_hour_cap, is_active, sort_order FROM commerce.subscription_plans WHERE id = $1
`

func (q *Queries) GetSubscriptionPlanByID(ctx context.Context, id uuid.UUID) (CommerceSubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getSubscriptionPlanByID, id)
	var i CommerceSubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.PriceIrr,
		&i.PeriodDays,
		&i.MonthlyHourCap,
		&i.IsActive,
		&i.SortOrder,
	)
	return i, err
}

const listActiveSubscriptionPlans = `-- name: ListActiveSubscriptionPlans :many
SELECT id, code, name, price_irr, period_days, monthly_hour_cap, is_active, sort_order FROM commerce.subscription_plans WHERE is_active ORDER BY sort_order
`

func (q *Queries) ListActiveSubscriptionPlans(ctx context.Context) ([]CommerceSubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listActiveSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceSubscriptionPlan
	for rows.Next() {
		var i CommerceSubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.PriceIrr,
			&i.PeriodDays,
			&i.MonthlyHourCap,
			&i.IsActive,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsDueForRenewal = `-- name: ListSubscriptionsDueForRenewal :many
SELECT id, user_id, plan_id, status, auto_renew_from_wallet, started_at, expires_at, hours_consumed, canceled_at, created_at, last_renewal_attempt_at, renewal_failures FROM commerce.subscriptions
WHERE auto_renew_from_wallet
  AND status IN ('active', 'expired')
  AND expires_at <= now() + make_interval(hours => $1::int)
  AND expires_at >  now() - make_interval(hours => $2::int)
  AND (
        last_renewal_attempt_at IS NULL
     OR last_renewal_attempt_at < now() - make_interval(hours => $3::int)
  )
ORDER BY expires_at
`

type ListSubscriptionsDueForRenewalParams struct {
	LookaheadHours  int32 `json:"lookahead_hours"`
	GraceHours      int32 `json:"grace_hours"`
	RetryAfterHours int32 `json:"retry_after_hours"`
}

// ListSubscriptionsDueForRenewal عمداً ردیف‌های **گذشته از سررسید** را هم
// برمی‌گرداند، نه فقط آن‌هایی که تا یک ساعت آینده سررسید می‌شوند.
//
// باگی که این حل می‌کند: نسخه قبلی فقط `status = 'active'` را می‌دید و
// expire هم ساعتی اجرا می‌شد. اگر worker چند ساعت پایین بود — یا صرفاً
// expire زودتر از renew اجرا می‌شد — اشتراک به 'expired' می‌رفت و
// sweep تمدید دیگر هرگز نمی‌دیدش. کاربری که تمدید خودکار خواسته بود
// بی‌صدا دسترسی‌اش را از دست می‌داد و هیچ‌کس خبردار نمی‌شد.
//
// حالا پنجره جبران (grace) هم اشتراک‌های تازه‌منقضی را برمی‌گرداند، و
// last_renewal_attempt_at جلوی ناخنک زدن ساعتی به کیف پول خالی را
// می‌گیرد.
func (q *Queries) ListSubscriptionsDueForRenewal(ctx context.Context, arg ListSubscriptionsDueForRenewalParams) ([]CommerceSubscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsDueForRenewal, arg.LookaheadHours, arg.GraceHours, arg.RetryAfterHours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceSubscription
	for rows.Next() {
		var i CommerceSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.AutoRenewFromWallet,
			&i.StartedAt,
			&i.ExpiresAt,
			&i.HoursConsumed,
			&i.CanceledAt,
			&i.CreatedAt,
			&i.LastRenewalAttemptAt,
			&i.RenewalFailures,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRenewalAttempt = `-- name: MarkRenewalAttempt :exec
UPDATE commerce.subscriptions
SET last_renewal_attempt_at = now(),
    renewal_failures = CASE WHEN $1::boolean THEN 0 ELSE renewal_failures + 1 END
WHERE id = $2
`

type MarkRenewalAttemptParams struct {
	Succeeded bool      `json:"succeeded"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) MarkRenewalAttempt(ctx context.Context, arg MarkRenewalAttemptParams) error {
	_, err := q.db.Exec(ctx, markRenewalAttempt, arg.Succeeded, arg.ID)
	return err
}

const reactivateSubscription = `-- name: ReactivateSubscription :exec
UPDATE commerce.subscriptions
SET status = 'active'
WHERE id = $1 AND status = 'expired'
`

// تمدید موفق باید اشتراکِ تازه‌منقضی را دوباره فعال کند، وگرنه کاربر
// پول داده و همچنان دسترسی ندارد.
func (q *Queries) ReactivateSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reactivateSubscription, id)
	return err
}
