// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO commerce.payments (user_id, provider, amount_irr, authority)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, provider, amount_irr, status, authority, reference_code, failure_reason, ledger_entry_id, created_at, settled_at
`

type CreatePaymentParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Provider  string    `json:"provider"`
	AmountIrr int64     `json:"amount_irr"`
	Authority *string   `json:"authority"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CommercePayment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.UserID,
		arg.Provider,
		arg.AmountIrr,
		arg.Authority,
	)
	var i CommercePayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AmountIrr,
		&i.Status,
		&i.Authority,
		&i.ReferenceCode,
		&i.FailureReason,
		&i.LedgerEntryID,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const createWalletLedgerEntry = `-- name: CreateWalletLedgerEntry :one
INSERT INTO commerce.wallet_ledger (user_id, entry_type, amount_irr, reason, reference_type, reference_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, entry_type, amount_irr, reason, reference_type, reference_id, created_at
`

type CreateWalletLedgerEntryParams struct {
	UserID        uuid.UUID   `json:"user_id"`
	EntryType     string      `json:"entry_type"`
	AmountIrr     int64       `json:"amount_irr"`
	Reason        string      `json:"reason"`
	ReferenceType *string     `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
}

func (q *Queries) CreateWalletLedgerEntry(ctx context.Context, arg CreateWalletLedgerEntryParams) (CommerceWalletLedger, error) {
	row := q.db.QueryRow(ctx, createWalletLedgerEntry,
		arg.UserID,
		arg.EntryType,
		arg.AmountIrr,
		arg.Reason,
		arg.ReferenceType,
		arg.ReferenceID,
	)
	var i CommerceWalletLedger
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EntryType,
		&i.AmountIrr,
		&i.Reason,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByAuthority = `-- name: GetPaymentByAuthority :one
SELECT id, user_id, provider, amount_irr, status, authority, reference_code, failure_reason, ledger_entry_id, created_at, settled_at FROM commerce.payments WHERE provider = $1 AND authority = $2
`

type GetPaymentByAuthorityParams struct {
	Provider  string  `json:"provider"`
	Authority *string `json:"authority"`
}

func (q *Queries) GetPaymentByAuthority(ctx context.Context, arg GetPaymentByAuthorityParams) (CommercePayment, error) {
	row := q.db.QueryRow(ctx, getPaymentByAuthority, arg.Provider, arg.Authority)
	var i CommercePayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AmountIrr,
		&i.Status,
		&i.Authority,
		&i.ReferenceCode,
		&i.FailureReason,
		&i.LedgerEntryID,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, user_id, provider, amount_irr, status, authority, reference_code, failure_reason, ledger_entry_id, created_at, settled_at FROM commerce.payments WHERE id = $1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (CommercePayment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i CommercePayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AmountIrr,
		&i.Status,
		&i.Authority,
		&i.ReferenceCode,
		&i.FailureReason,
		&i.LedgerEntryID,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const getWalletBalance = `-- name: GetWalletBalance :one
SELECT
    COALESCE(SUM(CASE WHEN entry_type = 'credit' THEN amount_irr ELSE -amount_irr END), 0)::bigint AS balance_irr
FROM commerce.wallet_ledger
WHERE user_id = $1
`

func (q *Queries) GetWalletBalance(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletBalance, userID)
	var balance_irr int64
	err := row.Scan(&balance_irr)
	return balance_irr, err
}

const listWalletLedgerForUser = `-- name: ListWalletLedgerForUser :many
SELECT id, user_id, entry_type, amount_irr, reason, reference_type, reference_id, created_at, count(*) OVER () AS total_count FROM commerce.wallet_ledger
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWalletLedgerForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListWalletLedgerForUserRow struct {
	ID            uuid.UUID   `json:"id"`
	UserID        uuid.UUID   `json:"user_id"`
	EntryType     string      `json:"entry_type"`
	AmountIrr     int64       `json:"amount_irr"`
	Reason        string      `json:"reason"`
	ReferenceType *string     `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
	CreatedAt     time.Time   `json:"created_at"`
	TotalCount    int64       `json:"total_count"`
}

func (q *Queries) ListWalletLedgerForUser(ctx context.Context, arg ListWalletLedgerForUserParams) ([]ListWalletLedgerForUserRow, error) {
	rows, err := q.db.Query(ctx, listWalletLedgerForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWalletLedgerForUserRow
	for rows.Next() {
		var i ListWalletLedgerForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EntryType,
			&i.AmountIrr,
			&i.Reason,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentForSettlement = `-- name: LockPaymentForSettlement :one
SELECT id, user_id, provider, amount_irr, status, authority, reference_code, failure_reason, ledger_entry_id, created_at, settled_at FROM commerce.payments WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockPaymentForSettlement(ctx context.Context, id uuid.UUID) (CommercePayment, error) {
	row := q.db.QueryRow(ctx, lockPaymentForSettlement, id)
	var i CommercePayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AmountIrr,
		&i.Status,
		&i.Authority,
		&i.ReferenceCode,
		&i.FailureReason,
		&i.LedgerEntryID,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const lockWallet = `-- name: LockWallet :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// LockWallet قفل مشورتی سطح تراکنش روی کیف پول یک کاربر می‌گیرد.
//
// بدون این، برداشت اتمیک نیست: دو درخواست هم‌زمان هر دو موجودی را کافی
// می‌بینند و هر دو ردیف debit می‌سازند — کیف پول منفی می‌شود و چون دفتر
// کل فقط‌افزودنی است، اصلاحش یعنی ثبت یک credit جبرانی و توضیح دادن به
// کاربر. یک ستون balance با CHECK این را حل نمی‌کرد چون تصمیم صریح
// 08-decisions.md نداشتن ستون balance است؛ قفل، همان تضمین را بدون
// شکستن آن تصمیم می‌دهد.
//
// hashtextextended به جای hashtext چون خروجی bigint می‌دهد و
// pg_advisory_xact_lock نسخه تک‌آرگومانی bigint دارد.
func (q *Queries) LockWallet(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, lockWallet, dollar_1)
	return err
}

const markPaymentFailed = `-- name: MarkPaymentFailed :one
UPDATE commerce.payments
SET status = 'failed', failure_reason = $2, settled_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, provider, amount_irr, status, authority, reference_code, failure_reason, ledger_entry_id, created_at, settled_at
`

type MarkPaymentFailedParams struct {
	ID            uuid.UUID `json:"id"`
	FailureReason *string   `json:"failure_reason"`
}

func (q *Queries) MarkPaymentFailed(ctx context.Context, arg MarkPaymentFailedParams) (CommercePayment, error) {
	row := q.db.QueryRow(ctx, markPaymentFailed, arg.ID, arg.FailureReason)
	var i CommercePayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AmountIrr,
		&i.Status,
		&i.Authority,
		&i.ReferenceCode,
		&i.FailureReason,
		&i.LedgerEntryID,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}

const markPaymentSucceeded = `-- name: MarkPaymentSucceeded :one
UPDATE commerce.payments
SET status = 'succeeded', reference_code = $2, ledger_entry_id = $3, settled_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, user_id, provider, amount_irr, status, authority, reference_code, failure_reason, ledger_entry_id, created_at, settled_at
`

type MarkPaymentSucceededParams struct {
	ID            uuid.UUID   `json:"id"`
	ReferenceCode *string     `json:"reference_code"`
	LedgerEntryID pgtype.UUID `json:"ledger_entry_id"`
}

func (q *Queries) MarkPaymentSucceeded(ctx context.Context, arg MarkPaymentSucceededParams) (CommercePayment, error) {
	row := q.db.QueryRow(ctx, markPaymentSucceeded, arg.ID, arg.ReferenceCode, arg.LedgerEntryID)
	var i CommercePayment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AmountIrr,
		&i.Status,
		&i.Authority,
		&i.ReferenceCode,
		&i.FailureReason,
		&i.LedgerEntryID,
		&i.CreatedAt,
		&i.SettledAt,
	)
	return i, err
}
