// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingest.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAIBook = `-- name: CreateAIBook :exec

INSERT INTO public.books (id, title, author, description, language, status, cover)
VALUES ($1, $2, $3, $4, $5, 'draft', $6)
`

type CreateAIBookParams struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Author      *string   `json:"author"`
	Description *string   `json:"description"`
	Language    string    `json:"language"`
	Cover       *string   `json:"cover"`
}

// ماژول ingest سه جدول را می‌نویسد:
//   - ingest.submissions — مال خودش
//   - public.books / public.book_documents — ورودی سرویس AI
//
// دومی استثناست و عمدی: جدول‌های public را alembic **می‌سازد**، ولی
// ردیف تحویل کار را ما می‌نویسیم، چون همان تراکنشی که فایل را ثبت
// می‌کند باید کاری را هم که سرویس AI قرار است انجام دهد ثبت کند. اگر
// این دو از هم جدا شوند، همان dual-write ای می‌شود که outbox برای حذفش
// ساخته شد.
func (q *Queries) CreateAIBook(ctx context.Context, arg CreateAIBookParams) error {
	_, err := q.db.Exec(ctx, createAIBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.Language,
		arg.Cover,
	)
	return err
}

const createAIDocument = `-- name: CreateAIDocument :exec
INSERT INTO public.book_documents (
    id, book_id, file_name, storage_key, mime_type, size, document_type, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'uploaded'
)
`

type CreateAIDocumentParams struct {
	ID           uuid.UUID   `json:"id"`
	BookID       uuid.UUID   `json:"book_id"`
	FileName     string      `json:"file_name"`
	StorageKey   string      `json:"storage_key"`
	MimeType     string      `json:"mime_type"`
	Size         int32       `json:"size"`
	DocumentType interface{} `json:"document_type"`
}

func (q *Queries) CreateAIDocument(ctx context.Context, arg CreateAIDocumentParams) error {
	_, err := q.db.Exec(ctx, createAIDocument,
		arg.ID,
		arg.BookID,
		arg.FileName,
		arg.StorageKey,
		arg.MimeType,
		arg.Size,
		arg.DocumentType,
	)
	return err
}

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO ingest.submissions (
    ai_book_id, ai_document_id, catalog_book_id, title, author, description,
    pdf_file_name, pdf_storage_key, pdf_size_bytes, cover_storage_key,
    want_tts, want_assistant, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13
)
RETURNING id, ai_book_id, ai_document_id, catalog_book_id, title, author, description, pdf_file_name, pdf_storage_key, pdf_size_bytes, cover_storage_key, want_tts, want_assistant, dispatch_status, dispatch_error, dispatched_at, created_by, created_at, updated_at, catalog_edition_id, audio_status, audio_error, audio_synced_at, audio_signature
`

type CreateSubmissionParams struct {
	AiBookID        uuid.UUID   `json:"ai_book_id"`
	AiDocumentID    uuid.UUID   `json:"ai_document_id"`
	CatalogBookID   pgtype.UUID `json:"catalog_book_id"`
	Title           string      `json:"title"`
	Author          *string     `json:"author"`
	Description     *string     `json:"description"`
	PdfFileName     string      `json:"pdf_file_name"`
	PdfStorageKey   string      `json:"pdf_storage_key"`
	PdfSizeBytes    int64       `json:"pdf_size_bytes"`
	CoverStorageKey *string     `json:"cover_storage_key"`
	WantTts         bool        `json:"want_tts"`
	WantAssistant   bool        `json:"want_assistant"`
	CreatedBy       *string     `json:"created_by"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (IngestSubmission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.AiBookID,
		arg.AiDocumentID,
		arg.CatalogBookID,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.PdfFileName,
		arg.PdfStorageKey,
		arg.PdfSizeBytes,
		arg.CoverStorageKey,
		arg.WantTts,
		arg.WantAssistant,
		arg.CreatedBy,
	)
	var i IngestSubmission
	err := row.Scan(
		&i.ID,
		&i.AiBookID,
		&i.AiDocumentID,
		&i.CatalogBookID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.PdfFileName,
		&i.PdfStorageKey,
		&i.PdfSizeBytes,
		&i.CoverStorageKey,
		&i.WantTts,
		&i.WantAssistant,
		&i.DispatchStatus,
		&i.DispatchError,
		&i.DispatchedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CatalogEditionID,
		&i.AudioStatus,
		&i.AudioError,
		&i.AudioSyncedAt,
		&i.AudioSignature,
	)
	return i, err
}

const getAIBook = `-- name: GetAIBook :one
SELECT id, title, author, description, status::text AS status
FROM public.books WHERE id = $1
`

type GetAIBookRow struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Author      *string   `json:"author"`
	Description *string   `json:"description"`
	Status      string    `json:"status"`
}

func (q *Queries) GetAIBook(ctx context.Context, id uuid.UUID) (GetAIBookRow, error) {
	row := q.db.QueryRow(ctx, getAIBook, id)
	var i GetAIBookRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.Status,
	)
	return i, err
}

const getCoverKey = `-- name: GetCoverKey :one
SELECT cover_storage_key FROM ingest.submissions WHERE id = $1
`

func (q *Queries) GetCoverKey(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getCoverKey, id)
	var cover_storage_key *string
	err := row.Scan(&cover_storage_key)
	return cover_storage_key, err
}

const listAIAudioAssets = `-- name: ListAIAudioAssets :many
SELECT
    a.id,
    a.storage_key,
    a.format,
    a.duration,
    a.status,
    a.chapter_id,
    c.title       AS chapter_title,
    c.order_index AS chapter_order
FROM public.audio_assets a
LEFT JOIN public.book_chapters c ON c.id = a.chapter_id
WHERE a.book_id = $1
ORDER BY c.order_index NULLS FIRST, a.created_at
`

type ListAIAudioAssetsRow struct {
	ID           uuid.UUID   `json:"id"`
	StorageKey   string      `json:"storage_key"`
	Format       string      `json:"format"`
	Duration     *float64    `json:"duration"`
	Status       string      `json:"status"`
	ChapterID    pgtype.UUID `json:"chapter_id"`
	ChapterTitle *string     `json:"chapter_title"`
	ChapterOrder *int32      `json:"chapter_order"`
}

// خروجی صوتی سرویس AI برای یک کتاب.
//
// ترتیب مهم است: فایل‌ها به ترتیب فصل به هم چسبانده می‌شوند و اگر ترتیب
// عوض شود کتاب با فصل هفتم شروع می‌شود. فصل‌های سمت AI order_index دارند؛
// فایل بدون فصل (کل کتاب در یک فایل) اول می‌آید چون در آن حالت تنها فایل است.
func (q *Queries) ListAIAudioAssets(ctx context.Context, bookID uuid.UUID) ([]ListAIAudioAssetsRow, error) {
	rows, err := q.db.Query(ctx, listAIAudioAssets, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAIAudioAssetsRow
	for rows.Next() {
		var i ListAIAudioAssetsRow
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.Format,
			&i.Duration,
			&i.Status,
			&i.ChapterID,
			&i.ChapterTitle,
			&i.ChapterOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAudioSyncCandidates = `-- name: ListAudioSyncCandidates :many
SELECT s.id
FROM ingest.submissions s
WHERE s.want_tts
  AND s.audio_status IN ('pending', 'failed')
  AND EXISTS (SELECT 1 FROM public.audio_assets a WHERE a.book_id = s.ai_book_id)
ORDER BY s.created_at
LIMIT $1
`

// کاندیداهای همگام‌سازی صوت: تیک TTS خورده، هنوز جا نیفتاده یا شکست خورده،
// و سرویس AI حداقل یک فایل صوتی برایش نوشته است. آخرین شرط جلوی این را
// می‌گیرد که sweep هر دو دقیقه سراغ کتابی برود که هنوز چیزی تولید نشده.
func (q *Queries) ListAudioSyncCandidates(ctx context.Context, pageLimit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAudioSyncCandidates, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobSteps = `-- name: ListJobSteps :many

SELECT step, status::text AS status, progress, attempt, error_message, started_at, completed_at
FROM public.job_steps
WHERE job_id = $1
ORDER BY created_at
`

type ListJobStepsRow struct {
	Step         string             `json:"step"`
	Status       string             `json:"status"`
	Progress     int32              `json:"progress"`
	Attempt      int32              `json:"attempt"`
	ErrorMessage *string            `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

// خواندن «ثبت + وضعیت job» در repository.go با pgx دستی نوشته شده، نه
// اینجا. دلیلش یک محدودیت واقعی sqlc است: ستونی که از LEFT JOIN یا
// زیرکوئری اسکالر می‌آید می‌تواند NULL باشد، ولی sqlc آن را از روی
// تعریف ستون مبدأ NOT NULL می‌بیند و کدی می‌سازد که سر اولین ثبتِ
// بدون job در Scan می‌شکند. تولید غلط را با دست اصلاح نمی‌کنیم چون
// generate بعدی پاکش می‌کند.
func (q *Queries) ListJobSteps(ctx context.Context, jobID uuid.UUID) ([]ListJobStepsRow, error) {
	rows, err := q.db.Query(ctx, listJobSteps, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobStepsRow
	for rows.Next() {
		var i ListJobStepsRow
		if err := rows.Scan(
			&i.Step,
			&i.Status,
			&i.Progress,
			&i.Attempt,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAudioFailed = `-- name: MarkAudioFailed :exec
UPDATE ingest.submissions
SET audio_status = 'failed', audio_error = $1, updated_at = now()
WHERE id = $2
`

type MarkAudioFailedParams struct {
	AudioError *string   `json:"audio_error"`
	ID         uuid.UUID `json:"id"`
}

func (q *Queries) MarkAudioFailed(ctx context.Context, arg MarkAudioFailedParams) error {
	_, err := q.db.Exec(ctx, markAudioFailed, arg.AudioError, arg.ID)
	return err
}

const markAudioPending = `-- name: MarkAudioPending :exec
UPDATE ingest.submissions
SET audio_status = 'pending', audio_error = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkAudioPending(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAudioPending, id)
	return err
}

const markAudioSynced = `-- name: MarkAudioSynced :exec
UPDATE ingest.submissions
SET catalog_edition_id = $1,
    audio_status       = 'synced',
    audio_error        = NULL,
    audio_signature    = $2,
    audio_synced_at    = now(),
    updated_at         = now()
WHERE id = $3
`

type MarkAudioSyncedParams struct {
	CatalogEditionID pgtype.UUID `json:"catalog_edition_id"`
	AudioSignature   *string     `json:"audio_signature"`
	ID               uuid.UUID   `json:"id"`
}

func (q *Queries) MarkAudioSynced(ctx context.Context, arg MarkAudioSyncedParams) error {
	_, err := q.db.Exec(ctx, markAudioSynced, arg.CatalogEditionID, arg.AudioSignature, arg.ID)
	return err
}

const markDispatchFailed = `-- name: MarkDispatchFailed :exec
UPDATE ingest.submissions
SET dispatch_status = 'failed', dispatch_error = $1, updated_at = now()
WHERE id = $2
`

type MarkDispatchFailedParams struct {
	DispatchError *string   `json:"dispatch_error"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) MarkDispatchFailed(ctx context.Context, arg MarkDispatchFailedParams) error {
	_, err := q.db.Exec(ctx, markDispatchFailed, arg.DispatchError, arg.ID)
	return err
}

const markDispatchPending = `-- name: MarkDispatchPending :exec
UPDATE ingest.submissions
SET dispatch_status = 'pending', dispatch_error = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDispatchPending(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDispatchPending, id)
	return err
}

const markDispatched = `-- name: MarkDispatched :exec
UPDATE ingest.submissions
SET dispatch_status = 'dispatched', dispatched_at = now(), dispatch_error = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDispatched(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDispatched, id)
	return err
}
