// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// ماژول ingest سه جدول را می‌نویسد:
	//   * ingest.submissions — مال خودش
	//   * public.books / public.book_documents — ورودی سرویس AI
	//
	// دومی استثناست و عمدی: جدول‌های public را alembic **می‌سازد**، ولی
	// ردیف تحویل کار را ما می‌نویسیم، چون همان تراکنشی که فایل را ثبت
	// می‌کند باید کاری را هم که سرویس AI قرار است انجام دهد ثبت کند. اگر
	// این دو از هم جدا شوند، همان dual-write ای می‌شود که outbox برای حذفش
	// ساخته شد.
	CreateAIBook(ctx context.Context, arg CreateAIBookParams) error
	CreateAIDocument(ctx context.Context, arg CreateAIDocumentParams) error
	CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (IngestSubmission, error)
	GetAIBook(ctx context.Context, id uuid.UUID) (GetAIBookRow, error)
	GetCoverKey(ctx context.Context, id uuid.UUID) (*string, error)
	// خروجی صوتی سرویس AI برای یک کتاب.
	//
	// ترتیب مهم است: فایل‌ها به ترتیب فصل به هم چسبانده می‌شوند و اگر ترتیب
	// عوض شود کتاب با فصل هفتم شروع می‌شود. فصل‌های سمت AI order_index دارند؛
	// فایل بدون فصل (کل کتاب در یک فایل) اول می‌آید چون در آن حالت تنها فایل است.
	ListAIAudioAssets(ctx context.Context, bookID uuid.UUID) ([]ListAIAudioAssetsRow, error)
	// کاندیداهای همگام‌سازی صوت: تیک TTS خورده، هنوز جا نیفتاده یا شکست خورده،
	// و سرویس AI حداقل یک فایل صوتی برایش نوشته است. آخرین شرط جلوی این را
	// می‌گیرد که sweep هر دو دقیقه سراغ کتابی برود که هنوز چیزی تولید نشده.
	ListAudioSyncCandidates(ctx context.Context, pageLimit int32) ([]uuid.UUID, error)
	// خواندن «ثبت + وضعیت job» در repository.go با pgx دستی نوشته شده، نه
	// اینجا. دلیلش یک محدودیت واقعی sqlc است: ستونی که از LEFT JOIN یا
	// زیرکوئری اسکالر می‌آید می‌تواند NULL باشد، ولی sqlc آن را از روی
	// تعریف ستون مبدأ NOT NULL می‌بیند و کدی می‌سازد که سر اولین ثبتِ
	// بدون job در Scan می‌شکند. تولید غلط را با دست اصلاح نمی‌کنیم چون
	// generate بعدی پاکش می‌کند.
	ListJobSteps(ctx context.Context, jobID uuid.UUID) ([]ListJobStepsRow, error)
	MarkAudioFailed(ctx context.Context, arg MarkAudioFailedParams) error
	MarkAudioPending(ctx context.Context, id uuid.UUID) error
	MarkAudioSynced(ctx context.Context, arg MarkAudioSyncedParams) error
	MarkDispatchFailed(ctx context.Context, arg MarkDispatchFailedParams) error
	MarkDispatchPending(ctx context.Context, id uuid.UUID) error
	MarkDispatched(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
