// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: demo.sql

package sqlcgen

import (
	"context"
)

const getDemoContinueListening = `-- name: GetDemoContinueListening :one
SELECT id, book_id, progress_percent FROM home.demo_continue_listening LIMIT 1
`

func (q *Queries) GetDemoContinueListening(ctx context.Context) (HomeDemoContinueListening, error) {
	row := q.db.QueryRow(ctx, getDemoContinueListening)
	var i HomeDemoContinueListening
	err := row.Scan(&i.ID, &i.BookID, &i.ProgressPercent)
	return i, err
}

const getDemoSample = `-- name: GetDemoSample :one
SELECT id, book_id, ai_tag FROM home.demo_sample LIMIT 1
`

func (q *Queries) GetDemoSample(ctx context.Context) (HomeDemoSample, error) {
	row := q.db.QueryRow(ctx, getDemoSample)
	var i HomeDemoSample
	err := row.Scan(&i.ID, &i.BookID, &i.AiTag)
	return i, err
}

const listDemoRecommendations = `-- name: ListDemoRecommendations :many
SELECT id, book_id, tag, type, sort_order FROM home.demo_recommendations ORDER BY sort_order
`

func (q *Queries) ListDemoRecommendations(ctx context.Context) ([]HomeDemoRecommendation, error) {
	rows, err := q.db.Query(ctx, listDemoRecommendations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeDemoRecommendation
	for rows.Next() {
		var i HomeDemoRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Tag,
			&i.Type,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
