// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package sqlcgen

import (
	"context"
)

const createLead = `-- name: CreateLead :one
INSERT INTO home.leads (
    full_name, phone_number, email, user_type, interest_tags, consent,
    source, landing_path, referrer, utm_source, utm_medium, utm_campaign
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, full_name, phone_number, email, user_type, interest_tags, consent, source, landing_path, referrer, utm_source, utm_medium, utm_campaign, created_at
`

type CreateLeadParams struct {
	FullName     string   `json:"full_name"`
	PhoneNumber  *string  `json:"phone_number"`
	Email        *string  `json:"email"`
	UserType     string   `json:"user_type"`
	InterestTags []string `json:"interest_tags"`
	Consent      bool     `json:"consent"`
	Source       *string  `json:"source"`
	LandingPath  *string  `json:"landing_path"`
	Referrer     *string  `json:"referrer"`
	UtmSource    *string  `json:"utm_source"`
	UtmMedium    *string  `json:"utm_medium"`
	UtmCampaign  *string  `json:"utm_campaign"`
}

func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (HomeLead, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.UserType,
		arg.InterestTags,
		arg.Consent,
		arg.Source,
		arg.LandingPath,
		arg.Referrer,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
	)
	var i HomeLead
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.UserType,
		&i.InterestTags,
		&i.Consent,
		&i.Source,
		&i.LandingPath,
		&i.Referrer,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.CreatedAt,
	)
	return i, err
}

const findLeadByEmail = `-- name: FindLeadByEmail :one
SELECT id, full_name, phone_number, email, user_type, interest_tags, consent, source, landing_path, referrer, utm_source, utm_medium, utm_campaign, created_at FROM home.leads WHERE email = $1
`

func (q *Queries) FindLeadByEmail(ctx context.Context, email *string) (HomeLead, error) {
	row := q.db.QueryRow(ctx, findLeadByEmail, email)
	var i HomeLead
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.UserType,
		&i.InterestTags,
		&i.Consent,
		&i.Source,
		&i.LandingPath,
		&i.Referrer,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.CreatedAt,
	)
	return i, err
}

const findLeadByPhoneNumber = `-- name: FindLeadByPhoneNumber :one
SELECT id, full_name, phone_number, email, user_type, interest_tags, consent, source, landing_path, referrer, utm_source, utm_medium, utm_campaign, created_at FROM home.leads WHERE phone_number = $1
`

func (q *Queries) FindLeadByPhoneNumber(ctx context.Context, phoneNumber *string) (HomeLead, error) {
	row := q.db.QueryRow(ctx, findLeadByPhoneNumber, phoneNumber)
	var i HomeLead
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.UserType,
		&i.InterestTags,
		&i.Consent,
		&i.Source,
		&i.LandingPath,
		&i.Referrer,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.CreatedAt,
	)
	return i, err
}
