// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: localization.sql

package sqlcgen

import (
	"context"
)

const getLocalizationContent = `-- name: GetLocalizationContent :one
SELECT id, title, subtitle FROM home.localization_content LIMIT 1
`

func (q *Queries) GetLocalizationContent(ctx context.Context) (HomeLocalizationContent, error) {
	row := q.db.QueryRow(ctx, getLocalizationContent)
	var i HomeLocalizationContent
	err := row.Scan(&i.ID, &i.Title, &i.Subtitle)
	return i, err
}

const listLocalizationLanguages = `-- name: ListLocalizationLanguages :many
SELECT code, label, sort_order FROM home.localization_languages ORDER BY sort_order
`

func (q *Queries) ListLocalizationLanguages(ctx context.Context) ([]HomeLocalizationLanguage, error) {
	rows, err := q.db.Query(ctx, listLocalizationLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeLocalizationLanguage
	for rows.Next() {
		var i HomeLocalizationLanguage
		if err := rows.Scan(&i.Code, &i.Label, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalizationSamples = `-- name: ListLocalizationSamples :many
SELECT id, title, cover_url, language_code, sort_order FROM home.localization_samples ORDER BY sort_order
`

func (q *Queries) ListLocalizationSamples(ctx context.Context) ([]HomeLocalizationSample, error) {
	rows, err := q.db.Query(ctx, listLocalizationSamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeLocalizationSample
	for rows.Next() {
		var i HomeLocalizationSample
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CoverUrl,
			&i.LanguageCode,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalizationTopics = `-- name: ListLocalizationTopics :many
SELECT id, topic, sort_order FROM home.localization_topics ORDER BY sort_order
`

func (q *Queries) ListLocalizationTopics(ctx context.Context) ([]HomeLocalizationTopic, error) {
	rows, err := q.db.Query(ctx, listLocalizationTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeLocalizationTopic
	for rows.Next() {
		var i HomeLocalizationTopic
		if err := rows.Scan(&i.ID, &i.Topic, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
