// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	CreateLead(ctx context.Context, arg CreateLeadParams) (HomeLead, error)
	FindLeadByEmail(ctx context.Context, email *string) (HomeLead, error)
	FindLeadByPhoneNumber(ctx context.Context, phoneNumber *string) (HomeLead, error)
	GetDemoContinueListening(ctx context.Context) (HomeDemoContinueListening, error)
	GetDemoSample(ctx context.Context) (HomeDemoSample, error)
	GetLocalizationContent(ctx context.Context) (HomeLocalizationContent, error)
	ListDemoRecommendations(ctx context.Context) ([]HomeDemoRecommendation, error)
	ListHomeStats(ctx context.Context) ([]HomeStat, error)
	ListLocalizationLanguages(ctx context.Context) ([]HomeLocalizationLanguage, error)
	ListLocalizationSamples(ctx context.Context) ([]HomeLocalizationSample, error)
	ListLocalizationTopics(ctx context.Context) ([]HomeLocalizationTopic, error)
	ListSocialProofPartners(ctx context.Context) ([]HomeSocialProofPartner, error)
	ListSocialProofStats(ctx context.Context) ([]HomeSocialProofStat, error)
	ListSocialProofTestimonials(ctx context.Context) ([]HomeSocialProofTestimonial, error)
}

var _ Querier = (*Queries)(nil)
