// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social_proof.sql

package sqlcgen

import (
	"context"
)

const listSocialProofPartners = `-- name: ListSocialProofPartners :many
SELECT id, name, logo_url, sort_order FROM home.social_proof_partners ORDER BY sort_order
`

func (q *Queries) ListSocialProofPartners(ctx context.Context) ([]HomeSocialProofPartner, error) {
	rows, err := q.db.Query(ctx, listSocialProofPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeSocialProofPartner
	for rows.Next() {
		var i HomeSocialProofPartner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LogoUrl,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialProofStats = `-- name: ListSocialProofStats :many
SELECT id, label, value, sort_order FROM home.social_proof_stats ORDER BY sort_order
`

func (q *Queries) ListSocialProofStats(ctx context.Context) ([]HomeSocialProofStat, error) {
	rows, err := q.db.Query(ctx, listSocialProofStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeSocialProofStat
	for rows.Next() {
		var i HomeSocialProofStat
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Value,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSocialProofTestimonials = `-- name: ListSocialProofTestimonials :many
SELECT id, name, role, message, avatar_url, sort_order FROM home.social_proof_testimonials ORDER BY sort_order
`

func (q *Queries) ListSocialProofTestimonials(ctx context.Context) ([]HomeSocialProofTestimonial, error) {
	rows, err := q.db.Query(ctx, listSocialProofTestimonials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeSocialProofTestimonial
	for rows.Next() {
		var i HomeSocialProofTestimonial
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Message,
			&i.AvatarUrl,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
