// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package sqlcgen

import (
	"context"
)

const listHomeStats = `-- name: ListHomeStats :many
SELECT key, label, value, display_value, sort_order FROM home.stats ORDER BY sort_order
`

func (q *Queries) ListHomeStats(ctx context.Context) ([]HomeStat, error) {
	rows, err := q.db.Query(ctx, listHomeStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeStat
	for rows.Next() {
		var i HomeStat
		if err := rows.Scan(
			&i.Key,
			&i.Label,
			&i.Value,
			&i.DisplayValue,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
